import tabula
import pandas as pd
import os
from PyPDF2 import PdfReader
from datetime import datetime
import re

# --- Stage 1: Data Extraction using tabula-py ---

def _get_report_date_from_pdf(pdf_path):
    """
    Extracts the report date from the first page of the PDF.
    Expected format in PDF: 'for the date 19.04.2025.'
    Target format for CSV: 'M/D/YYYY'
    """
    try:
        reader = PdfReader(pdf_path)
        first_page_text = reader.pages[0].extract_text()
        match = re.search(r"for the date (\d{2}\.\d{2}\.\d{4})", first_page_text)
        if match:
            date_str_ddmmyyyy = match.group(1)
            # Convert DD.MM.YYYY to M/D/YYYY
            day, month, year = date_str_ddmmyyyy.split('.')
            return f"{int(month)}/{int(day)}/{year}"
        print("Warning: Could not find report date in PDF.")
        return "Unknown Date"
    except Exception as e:
        print(f"Error extracting report date: {e}")
        return "Unknown Date"

def extract_and_process_tables():
    """Extract and process tables from PDF using tabula-py."""
    pdf_path = "sample input/19.04.25_NLDC_PSP.pdf"
    reader = PdfReader(pdf_path)
    num_pages = len(reader.pages)

    processed_tables = {}

    print(f"Processing {num_pages} pages...")

    report_date = _get_report_date_from_pdf(pdf_path)

    for page in range(1, num_pages + 1): # tabula pages are 1-indexed
        try:
            tables = tabula.read_pdf(
                pdf_path,
                pages=page,
                multiple_tables=True,
                guess=True,
                lattice=True,
                stream=True
            )

            for table_idx, table in enumerate(tables):
                processed_tables[f"page_{page}_table_{table_idx}"] = table
            print(f"Processed page {page}. Found {len(tables)} tables.")

        except Exception as e:
            print(f"Error processing page {page}: {str(e)}")

    return processed_tables, report_date

# --- Stage 2: Identifying and Pre-processing Raw Tables ---

def identify_and_preprocess_raw_tables(raw_tables_dict):
    """
    Identifies and maps raw DataFrames from tabula's output
    to their logical table names based on provided key mapping.
    This function will now pass raw DataFrames without generic header cleaning,
    allowing specific transformations to handle headers.
    """
    identified_tables = {}

    # IMPORTANT: You MUST replace these placeholder keys (e.g., 'page_2_table_0')
    # with the actual keys generated by your `extract_and_process_tables()` function.
    # Run `print(raw_tables_dict.keys())` after extraction to get the exact keys.

    table_key_to_logical_name_map = {
        'page_2_table_0': 'A. Power Supply Position at All India and Regional level',
        'page_2_table_1': 'B. Frequency Profile (%)',
        'page_2_table_2': 'C. Power Supply Position in States',
        'page_2_table_3': 'D. Transnational Exchanges (MU) - Import(+ve)/Export(-ve)',
        'page_2_table_4': 'E. Import/Export by Regions (in MU) - Import(+ve)/Export(-ve); OD(+)/UD(-)',
        'page_2_table_5': 'F. Generation Outage(MW)',
        'page_2_table_6': 'G. Sourcewise generation (Gross) (MU)',
        'page_2_table_7': 'G. Share of RE and Non-fossil',
        'page_2_table_8': 'H. All India Demand Diversity Factor',
        'page_2_table_9': 'I. All India Peak Demand and shortage at Solar and Non-Solar Hour',
        'page_3_table_0': 'Intra-national Exchange',
        'page_3_table_1': 'International Exchange',
        'page_4_table_0': 'Export From India (in MU)',
        'page_4_table_1': 'Import by India(in MU)',
        'page_4_table_2': 'Net from India(in MU)',
        'page_5_table_0': '15 Min (INSTANTANEOUS) ALL INDIA GRID FREQUENCY, GENERATION & DEMAND MET (SCADA DATA)',
        'page_1_table_0': 'GARBAGE_TO_SKIP' # Example for '10' if it's indeed page 1, table 0
    }

    for tabula_key, df in raw_tables_dict.items():
        logical_name = table_key_to_logical_name_map.get(tabula_key)

        if logical_name and logical_name != 'GARBAGE_TO_SKIP':
            # --- REMOVED GENERIC HEADER CLEANING FROM HERE ---
            # DataFrames are passed as-is from tabula.
            # Specific header processing will happen in transform_ methods.

            # Still remove empty rows/columns that tabula might create, as these are generic artifacts
            # that don't depend on specific table structure.
            if not df.empty:
                df = df.dropna(axis=1, how='all') # Drop all-NA columns
                df = df.dropna(axis=0, how='all') # Drop all-NA rows
            
            identified_tables[logical_name] = df
            print(f"Identified table: {logical_name} from raw key: {tabula_key}")
        elif logical_name == 'GARBAGE_TO_SKIP':
            print(f"Skipping garbage table: {tabula_key}")
        else:
            print(f"No specific mapping found for raw key: {tabula_key}. Skipping or consider adding to map.")

    print(f"Identified {len(identified_tables)} key tables for transformation.")
    return identified_tables

# --- Stage 3: Data Transformation Functions (Adjusted for raw input) ---

class PSPTransformer:
    def __init__(self, report_date):
        self.report_date = report_date
        self.all_processed_dfs = []

    def _clean_column_names(self, df_columns):
        """
        Cleans a list of column names by stripping whitespace, replacing newlines,
        and removing special characters.
        Takes a list-like object of column names.
        """
        cleaned_cols = []
        for col in df_columns:
            cleaned_col = str(col).strip().replace('\n', ' ').replace('*', '').replace('(', '').replace(')', '')
            cleaned_cols.append(cleaned_col)
        return cleaned_cols

    def _add_common_cols(self, df, table_name):
        df['Date'] = self.report_date
        df['Table Name'] = table_name
        return df

    def transform_states(self, raw_df):
        """
        Transforms the raw DataFrame from 'C. Power Supply Position in States'
        into the 'States' table format of the CSV.
        Logic: Ensure each row has 9 values; prepend NaN if only 8 values.
        Assign region based on states mapping, then fill down.
        """
        df = raw_df.copy()

        # The raw_df now comes directly from tabula.
        # It might have its own headers (from tabula's guess=True) or default names.
        # It also might have a header row from the PDF still in the data.

        # Identify the actual header row from the PDF (e.g., 'Region', 'States', 'Max.Demand...')
        # Look for a row that contains 'States' or 'Maximum Demand' to identify the header row.
        # header_row_idx = -1
        # for r_idx in range(min(df.shape[0], 3)): # Check first few rows for header
        #     row_str = " ".join(df.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "States" in row_str and ("Demand" in row_str or "Met" in row_str):
        #         header_row_idx = r_idx
        #         break
        
        # if header_row_idx != -1:
        #     # Set columns using the identified header row and clean them
        #     df.columns = self._clean_column_names(df.iloc[header_row_idx])
        #     df = df[header_row_idx + 1:].reset_index(drop=True)
        # else:
        #     print(f"Warning: No clear header row found for States table. Assuming first row is header.")
        #     df.columns = self._clean_column_names(df.iloc[0])
        #     df = df[1:].reset_index(drop=True)


        # Define the 9 target CSV columns.
        target_csv_columns = [
            'Region', 'States', 'Maximum Demand (MW)', 'Shortage (MW)', 'Energy Met (MU)',
            'Drawal Schedule (MU)', 'OD(+)/UD(-) (MU)', 'Max OD (MW)', 'Energy Shortage (MU)'
        ]
        df.columns = target_csv_columns

        # Map current df columns to target_csv_columns
        # This is robust if tabula renames some columns slightly (e.g., 'Max.Demand' to 'Max.Demand Met')
        # column_remapping = {
        #     'Region': 'Region', # If tabula correctly extracts 'Region'
        #     'States': 'States',
        #     'Max.Demand Met during the day (MW)': 'Maximum Demand (MW)',
        #     'Shortage during maximum Demand (MW)': 'Shortage (MW)',
        #     'Energy Met (MU)': 'Energy Met (MU)',
        #     'Drawal Schedule (MU)': 'Drawal Schedule (MU)',
        #     'OD(+)/UD(+) (MT))': 'OD(+)/UD(-) (MU)', # Correcting typo and normalizing
        #     'Max OD (MW)': 'Max OD (MW)',
        #     'Energy Shortage (MU)': 'Energy Shortage (MU)'
        #     # Add other potential raw column names from tabula if they differ
        #     # E.g., 'Max.Demand'
        # }
        
        # # Apply renaming to columns that exist in the DataFrame
        # df.rename(columns={k: v for k, v in column_remapping.items() if k in df.columns}, inplace=True)

        # processed_rows_data = []

        # # Iterate through each row to adjust its length to 9 columns if needed.
        # for _, row in df.iterrows():
        #     row_values = row.tolist() # Get all values in the row as a list

        #     # Clean each string value in the row first, to handle potential blank strings
        #     row_values = [str(val).strip() if pd.notna(val) else None for val in row_values]

        #     # Remove trailing None/empty strings that might be artifacts
        #     while row_values and (row_values[-1] is None or row_values[-1] == ''):
        #         row_values.pop()

        #     current_num_values = len(row_values)

        #     if current_num_values == len(target_csv_columns):
        #         # Row already has 9 values, assume it's correctly aligned (Region, States, ...)
        #         processed_rows_data.append(row_values)
        #     elif current_num_values == len(target_csv_columns) - 1:
        #         # Row has 8 values, implying the 'Region' column (first column) is missing.
        #         # Prepend a NaN (or None) to align it.
        #         processed_row = [None] + row_values
        #         processed_rows_data.append(processed_row)
        #     else:
        #         print(f"Warning: Row has unexpected number of values ({current_num_values}). Expected 8 or 9. Row: {row_values}")
        #         # Pad or truncate to target length
        #         if current_num_values < len(target_csv_columns):
        #             processed_row = row_values + [None] * (len(target_csv_columns) - current_num_values)
        #         else:
        #             processed_row = row_values[:len(target_csv_columns)]
        #         processed_rows_data.append(processed_row)

        # if not processed_rows_data:
        #     print("No rows processed for States table after length adjustment.")
        #     return pd.DataFrame()

        # df_processed = pd.DataFrame(processed_rows_data, columns=target_csv_columns)

        

        mask = (~df['Region'].isin(['NR', 'WR', 'SR', 'ER', 'NER'])) & (df['Region'].notna())
        idx = df.index[mask]

        for i in idx:
            df.iloc[i,:] = df.iloc[i,:].shift(1, fill_value=pd.NA)
        # Mapping for Regions based on states (from your prior input)
        region_mapping = {
            'Punjab': 'NR', 'Haryana': 'NR', 'Rajasthan': 'NR', 'Delhi': 'NR', 'UP': 'NR',
            'Uttarakhand': 'NR', 'HP': 'NR', 'J&K(UT) & Ladakh (UT)': 'NR', 'Chandigarh': 'NR', 'Railways NR ISTS': 'NR',
            'Chhattisgarh': 'WR', 'Gujarat': 'WR', 'MP': 'WR', 'Maharashtra': 'WR', 'Goa': 'WR',
            'DNHDDPDCL': 'WR', 'AMNSIL': 'WR', 'BALCO': 'WR', 'RIL JAMNAGAR': 'WR',
            'Andhra Pradesh': 'SR', 'Telangana': 'SR', 'Karnataka': 'SR', 'Kerala': 'SR', 'Tamil Nadu': 'SR', 'Puducherry': 'SR',
            'Bihar': 'ER', 'DVC': 'ER', 'Jharkhand': 'ER', 'Odisha': 'ER', 'West Bengal': 'ER', 'Sikkim': 'ER', 'Railways ER ISTS': 'ER',
            'Arunachal Pradesh': 'NER', 'Assam': 'NER', 'Manipur': 'NER', 'Meghalaya': 'NER', 'Mizoram': 'NER', 'Nagaland': 'NER', 'Tripura': 'NER'
        }

        # # Apply region mapping, prioritizing the map for initial assignment or correction
        # df['Region'] = df.apply(
        #     lambda row: region_mapping.get(row['States'], row['Region']), axis=1
        # )
        # df['Region'] = df['Region'].fillna('Unknown Region')

        # Convert numeric columns
        numeric_cols = [
            'Maximum Demand (MW)', 'Shortage (MW)', 'Energy Met (MU)',
            'Drawal Schedule (MU)', 'OD(+)/UD(-) (MU)', 'Max OD (MW)', 'Energy Shortage (MU)'
        ]
        for col in numeric_cols:
            df[col] = df[col].astype(str).str.replace(',', '').str.replace(' ', '').str.strip()
            df[col] = df[col].apply(lambda x: re.sub(r'\.+', '.', x).rstrip('.') if isinstance(x, str) else x)
            df[col] = pd.to_numeric(df[col], errors='coerce')

        df = self._add_common_cols(df, 'States')

        # Fill down the 'Region' column (which is the first column now)
        df['Region'] = df['Region'].replace('', pd.NA).ffill()

        final_df = df[['Date', 'Table Name', 'Region', 'States', 'Maximum Demand (MW)', 'Shortage (MW)',
                                 'Energy Met (MU)', 'Drawal Schedule (MU)', 'OD(+)/UD(-) (MU)', 'Max OD (MW)', 'Energy Shortage (MU)']]
        return final_df

    def transform_international_net(self, raw_df):
        """
        Transforms the raw DataFrame from 'D. Transnational Exchanges (MU)'
        into the 'International NET' table format of the CSV.
        """
        df = raw_df.copy()
    
        numeric_list = df.iloc[0,1:].tolist() + df.iloc[1,1:].tolist()

        # # Identify the actual header row from the PDF (e.g., 'Date', 'Bhutan (MU)', 'Nepal (MU)', ...)
        # header_row_idx = -1
        # for r_idx in range(min(df.shape[0], 3)): # Check first few rows
        #     row_str = " ".join(df.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Bhutan (MU)" in row_str and "Nepal (MU)" in row_str:
        #         header_row_idx = r_idx
        #         break
        
        # if header_row_idx != -1:
        #     df.columns = self._clean_column_names(df.iloc[header_row_idx])
        #     df = df[header_row_idx + 1:].reset_index(drop=True)
        # else:
        #     print(f"Warning: No clear header row found for International NET table. Assuming first row is header.")
        #     df.columns = self._clean_column_names(df.iloc[0])
        #     df = df[1:].reset_index(drop=True)

        target_columns = [
            'Bhutan (MU)', 'Nepal (MU)', 'Bangladesh(MU)',
            'Godda (Bangladesh) (MU)', 'Bhutan Peak (MW)', 'Nepal Peak (MW)',
            'Bangladesh Peak (MW)', 'Godda (Bangladesh) Peak (MW)'
        ]

        df_processed = pd.DataFrame(dict(zip(target_columns, numeric_list)), index=[0], columns=target_columns)

        # # raw_to_target_col_map = {
        # #     'Date': 'Date',
        # #     'Bhutan (MU)': 'Bhutan (MU)',
        # #     'Nepal (MU)': 'Nepal (MU)',
        # #     'Bangladesh(MU)': 'Bangladesh(MU)',
        # #     'Godda (Bangladesh) (MU)': 'Godda (Bangladesh) (MU)',
        # #     'Bhutan Peak (MW)': 'Bhutan Peak (MW)',
        # #     'Nepal Peak (MW)': 'Nepal Peak (MW)',
        # #     'Bangladesh Peak (MW)': 'Bangladesh Peak (MW)',
        # #     'Godda (Bangladesh) Peak (MW)': 'Godda (Bangladesh) Peak (MW)'
        # # }
        
        # df.rename(columns={k: v for k, v in raw_to_target_col_map.items() if k in df.columns}, inplace=True)

        # for col in target_columns:
        #     if col not in df.columns:
        #         df[col] = None

        # df = df[target_columns].copy()

        # for col in target_columns[1:]:
        #     df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

        df_processed = self._add_common_cols(df_processed, 'International NET')

        final_df = df_processed[['Date', 'Table Name'] + target_columns]
        return final_df

    def transform_regional_summary(self, raw_df_A, raw_df_B, raw_df_E, raw_df_F, raw_df_G_main, raw_df_G_share, raw_df_H, raw_df_I):
        """
        Transforms raw DataFrames from A, B, E, F, G (two parts), H, I into
        the 'India', 'NR', 'WR', 'SR', 'ER', 'NER' tables for the CSV.
        This is the most complex transformation.
        """
        final_regional_data = []
        
        data_sources = []

        # Process A
        df_a = raw_df_A.copy()

        # header_row_idx_a = -1
        # for r_idx in range(min(df_a.shape[0], 3)):
        #     row_str = " ".join(df_a.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Evening Peak (MW)" in row_str and "TOTAL" in row_str:
        #         header_row_idx_a = r_idx
        #         break
        # if header_row_idx_a != -1:
        #     df_a.columns = self._clean_column_names(df_a.iloc[header_row_idx_a])
        #     df_a = df_a[header_row_idx_a + 1:].reset_index(drop=True)
        # else:
        #     print("Warning: No clear header for Table A. Assuming first row is header.")
        #     df_a.columns = self._clean_column_names(df_a.iloc[0])
        #     df_a = df_a[1:].reset_index(drop=True)
        data_sources.append((df_a, 'A'))

        # Process E
        df_e = raw_df_E.copy()
        # header_row_idx_e = -1
        # for r_idx in range(min(df_e.shape[0], 3)):
        #     row_str = " ".join(df_e.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Schedule MU)" in row_str and "OD/UD(MU" in row_str: # Corrected from OD/UD(MT))
        #         header_row_idx_e = r_idx
        #         break
        # if header_row_idx_e != -1:
        #     df_e.columns = self._clean_column_names(df_e.iloc[header_row_idx_e])
        #     df_e = df_e[header_row_idx_e + 1:].reset_index(drop=True)
        # else:
        #     print("Warning: No clear header for Table E. Assuming first row is header.")
        #     df_e.columns = self._clean_column_names(df_e.iloc[0])
        #     df_e = df_e[1:].reset_index(drop=True)
        data_sources.append((df_e, 'E'))

        # Process F
        df_f = raw_df_F.copy()
        # header_row_idx_f = -1
        # for r_idx in range(min(df_f.shape[0], 3)):
        #     row_str = " ".join(df_f.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Central Sector" in row_str and "Total" in row_str and "Share" in row_str:
        #         header_row_idx_f = r_idx
        #         break
        # if header_row_idx_f != -1:
        #     df_f.columns = self._clean_column_names(df_f.iloc[header_row_idx_f])
        #     df_f = df_f[header_row_idx_f + 1:].reset_index(drop=True)
        # else:
        #     print("Warning: No clear header for Table F. Assuming first row is header.")
        #     df_f.columns = self._clean_column_names(df_f.iloc[0])
        #     df_f = df_f[1:].reset_index(drop=True)
        data_sources.append((df_f, 'F'))

        # Process G_main
        df_g_main = raw_df_G_main.copy()
        # header_row_idx_g_main = -1
        # for r_idx in range(min(df_g_main.shape[0], 3)):
        #     row_str = " ".join(df_g_main.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Coal" in row_str and "Lignite" in row_str and "All India" in row_str:
        #         header_row_idx_g_main = r_idx
        #         break
        # if header_row_idx_g_main != -1:
        #     df_g_main.columns = self._clean_column_names(df_g_main.iloc[header_row_idx_g_main])
        #     df_g_main = df_g_main[header_row_idx_g_main + 1:].reset_index(drop=True)
        # else:
        #     print("Warning: No clear header for Table G_main. Assuming first row is header.")
        #     df_g_main.columns = self._clean_column_names(df_g_main.iloc[0])
        #     df_g_main = df_g_main[1:].reset_index(drop=True)
        data_sources.append((df_g_main, 'G_Main'))

        # Process G_share
        df_g_share = raw_df_G_share.copy()

        # Step 1: Prepend the header row back to the data
        df_g_share.loc[-1] = df_g_share.columns  # Add original header as the first row
        df_g_share.columns = df_g_main.columns[0:df_g_share.shape[1]]
        df_g_share.index = df_g_share.index + 1  # Reindex
        df_g_share = df_g_share.sort_index()

        # header_row_idx_g_share = -1
        # for r_idx in range(min(df_g_share.shape[0], 3)):
        #     row_str = " ".join(df_g_share.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Share of RES" in row_str and "Non-fossil" in row_str:
        #         header_row_idx_g_share = r_idx
        #         break
        # if header_row_idx_g_share != -1:
        #     df_g_share.columns = self._clean_column_names(df_g_share.iloc[header_row_idx_g_share])
        #     df_g_share = df_g_share[header_row_idx_g_share + 1:].reset_index(drop=True)
        # else:
        #     print("Warning: No clear header for Table G_share. Assuming first row is header.")
        #     df_g_share.columns = self._clean_column_names(df_g_share.iloc[0])
        #     df_g_share = df_g_share[1:].reset_index(drop=True)
        data_sources.append((df_g_share, 'G_Share'))


        for df_source, source_type in data_sources:
            df_temp = df_source.copy()
            
            metrics_col = df_temp.columns[0]
            regions_cols = [col for col in df_temp.columns if col != metrics_col]

            df_melted = df_temp.melt(
                id_vars=[metrics_col],
                value_vars=regions_cols,
                var_name='Region',
                value_name='Value'
            )
            df_melted['Metric'] = df_melted[metrics_col]
            
            df_melted['Region'] = df_melted['Region'].replace('TOTAL', 'India').replace('All India', 'India').replace('% Share', 'India')
            
            final_regional_data.append(df_melted[['Metric', 'Region', 'Value']])
            
        combined_melted_df = pd.concat(final_regional_data, ignore_index=True)

        # --- Process Table B: Frequency Profile (%) ---
        df_b = raw_df_B.copy()

        # header_row_idx_b = -1
        # for r_idx in range(min(df_b.shape[0], 3)):
        #     row_str = " ".join(df_b.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Region" in row_str and "FVI" in row_str and "<49.7" in row_str:
        #         header_row_idx_b = r_idx
        #         break
        # if header_row_idx_b != -1:
        #     df_b.columns = self._clean_column_names(df_b.iloc[header_row_idx_b])
        #     df_b = df_b[header_row_idx_b + 1:].reset_index(drop=True)
        # else:
        #     print("Warning: No clear header for Table B. Assuming first row is header.")
        #     df_b.columns = self._clean_column_names(df_b.iloc[0])
        #     df_b = df_b[1:].reset_index(drop=True)

        all_india_freq_row = df_b[df_b['Region'] == 'All India'].iloc[0]
        target_freq_cols = ['Region', 'FVI', 'Frequency (<49.7)', 'Frequency (49.7 - 49.8)', 'Frequency (49.8 - 49.9)',
                            'Frequency (< 49.9)', 'Frequency (49.9 - 50.05)', 'Frequency (> 50.05)']
        
        # freq_metrics_map = {
        #     'FVI': 'FVA', 
        #     '49.7': 'Frequency (<49.7)', # Raw column name '<49.7' is often just '49.7' in tabula
        #     '49.7-49.8': 'Frequency (49.7 - 49.8)',
        #     '49.8-49.9': 'Frequency (49.8 - 49.9)',
        #     '49.9': 'Frequency (< 49.9)',
        #     '49.9-50.05': 'Frequency (49.9 - 50.05)',
        #     '50.05': 'Frequency (> 50.05)' # Raw column name '>50.05' might be '50.05'
        # }

        # for raw_metric, csv_metric in freq_metrics_map.items():
        #     if raw_metric in all_india_freq_row:
        #         combined_melted_df.loc[len(combined_melted_df)] = {
        #             'Metric': csv_metric,
        #             'Region': 'India',
        #             'Value': all_india_freq_row[raw_metric]
        #         }

        for i in range(1,len(target_freq_cols)):
            combined_melted_df.loc[len(combined_melted_df)] = {
                'Metric': target_freq_cols[i],
                'Region': 'India',
                'Value': all_india_freq_row[i]
            }

        # --- Process Table H: All India Demand Diversity Factor ---
        df_h = raw_df_H.copy()

        # header_row_idx_h = -1
        # for r_idx in range(min(df_h.shape[0], 3)):
        #     row_str = " ".join(df_h.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Based on Regional" in row_str and "Based on State" in row_str:
        #         header_row_idx_h = r_idx
        #         break
        # if header_row_idx_h != -1: # This table often has no real header, first row is data
        #     df_h = df_h[header_row_idx_h:].reset_index(drop=True) # Keep from this row onwards
        # # For H, often tabula extracts just the values, or values with first column being description.
        # # Assuming df_h is like: ['Based on Regional Max Demands', '1.057']
        
        combined_melted_df.loc[len(combined_melted_df)] = {
            'Metric': 'Region DDF',
            'Region': 'India',
            'Value': df_h.columns[1]
        }
        combined_melted_df.loc[len(combined_melted_df)] = {
            'Metric': 'States DDF',
            'Region': 'India',
            'Value': df_h.iloc[0, 1]
        }
        
        # --- Process Table I: All India Peak Demand and shortage at Solar and Non-Solar Hour ---
        df_i = raw_df_I.copy()

        # header_row_idx_i = -1
        # for r_idx in range(min(df_i.shape[0], 3)):
        #     row_str = " ".join(df_i.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Max Demand Met" in row_str and "Shortage" in row_str and "Time" in row_str:
        #         header_row_idx_i = r_idx
        #         break
        # if header_row_idx_i != -1:
        #     df_i.columns = self._clean_column_names(df_i.iloc[header_row_idx_i])
        #     df_i = df_i[header_row_idx_i + 1:].reset_index(drop=True)
        # else:
        #     print("Warning: No clear header for Table I. Assuming first row is header.")
        #     df_i.columns = self._clean_column_names(df_i.iloc[0])
        #     df_i = df_i[1:].reset_index(drop=True)


        hour_types = df_i.iloc[:, 0].tolist() # Assuming first column is the hour type ('Solar hr', 'Non-Solar hr')
        
        for idx, hour_type in enumerate(hour_types):
            row_data = df_i.iloc[idx, 1:].tolist() 

            # metric_suffixes = ['Max Demand (MW)', 'Max Demand Time', 'Shortage (MW)']
            # # Map raw column names for I to CSV names (e.g., 'Max Demand Met MW)')
            # raw_i_col_names_map = {
            #     'Max Demand Met(MW)': 'Max Demand (MW)',
            #     'Time': 'Max Demand Time',
            #     'Shortage(MW)': 'Shortage (MW)'
            # }
            
            # Use actual column names from df_i for row_data access
            # This requires df_i to have correctly set headers.
            if 'Max Demand Met(MW)' in df_i.columns and 'Time' in df_i.columns and 'Shortage(MW)' in df_i.columns:
                combined_melted_df.loc[len(combined_melted_df)] = {
                    'Metric': f"{hour_type.replace(' hr', 'HR')} Max Demand (MW)",
                    'Region': 'India',
                    'Value': df_i.loc[idx, 'Max Demand Met(MW)']
                }
                combined_melted_df.loc[len(combined_melted_df)] = {
                    'Metric': f"{hour_type.replace(' hr', 'HR')} Max Demand Time",
                    'Region': 'India',
                    'Value': df_i.loc[idx, 'Time']
                }
                combined_melted_df.loc[len(combined_melted_df)] = {
                    'Metric': f"{hour_type.replace(' hr', 'HR')} Shortage (MW)",
                    'Region': 'India',
                    'Value': df_i.loc[idx, 'Shortage(MW)']
                }


        final_regional_dfs = []
        # Get original Metric order as they appear in the data
        original_metric_order = combined_melted_df['Metric'].drop_duplicates().tolist()

        for region_name in combined_melted_df['Region'].unique():
            df_region_specific = combined_melted_df[combined_melted_df['Region'] == region_name].copy()
            
            df_pivoted = df_region_specific.pivot_table(
                index='Region',
                columns='Metric',
                values='Value',
                aggfunc='first'
            ).reset_index()
            
            df_pivoted.rename(columns={'Region': 'Table Name'}, inplace=True)
            df_pivoted['Date'] = self.report_date
            
            # Reorder columns: ['Table Name', <metrics in original order>, 'Date']
            ordered_columns = ['Date', 'Table Name'] + original_metric_order
            df_pivoted = df_pivoted.reindex(columns=ordered_columns)

            final_regional_dfs.append(df_pivoted)

        final_output_df = pd.concat(final_regional_dfs, ignore_index=True)

        # final_csv_cols_regional = [
        #     'Date', 'Table Name', 'Evening Peak (MW)', 'Peak Shortage (MW)', 'Energy Met (MU)',
        #     'Hydro Gen (MU)', 'Wind Gen (MU)', 'Solar Gen (MU)*', 'Energy Shortage (MU)',
        #     'Maximum Demand (MW)', 'Max Demand Timestamp', 'Import Scheduled (MU)', 'Import Actual (MU)',
        #     'OD/UD (MU)', 'Central Outage (MW)', 'State Outage (MW)', 'Total Outage (MW)',
        #     'Coal (MU)', 'Lignite (MU)', 'Hydro (MU)', 'Nuclear (MU)', 'Gas, Naptha & Diesel (MU)',
        #     'RES (Wind, Solar, Biomass & Others) (MU)', 'Total (MU)', 'RE Share (%)',
        #     'Non-fossil Share (%)', 'FVA', 'Frequency (<49.7)', 'Frequency (49.7 - 49.8)',
        #     'Frequency (49.8 - 49.9)', 'Frequency (< 49.9)', 'Frequency (49.9 - 50.05)',
        #     'Frequency (> 50.05)', 'Region DDF', 'States DDF', 'SolarHR Max Demand (MW)',
        #     'Non-SolarHR Max Demand (MW)', 'SolarHR Max Demand Time', 'Non-SolarHR Max Demand Time',
        #     'SolarHR Shortage (MW)', 'Non-SolarHR Shortage (MW)'
        # ]
        
        # for col in final_csv_cols_regional:
        #     if col not in final_output_df.columns:
        #         final_output_df[col] = None
        
        # for col in final_csv_cols_regional:
        #     if col not in ['Date', 'Table Name', 'Max Demand Timestamp', 'SolarHR Max Demand Time', 'Non-SolarHR Max Demand Time']:
        #         final_output_df[col] = pd.to_numeric(final_output_df[col], errors='coerce')


        return final_output_df

    def transform_inter_region(self, raw_df):
        """
        Transforms the raw DataFrame from 'Intra-national Exchange' (Page 3)
        into the 'Inter-Region' table format of the CSV.
        """
        df = raw_df.copy()


        # Identify the header row based on keywords
        # header_row_idx = -1
        # for r_idx in range(min(df.shape[0], 5)): # Check first few rows, maybe up to 5 for multi-line
        #     row_str = " ".join(df.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "Voltage Level" in row_str and "Line Details" in row_str and "Max Import" in row_str:
        #         header_row_idx = r_idx
        #         break
        
        # if header_row_idx != -1:
        #     df.columns = self._clean_column_names(df.iloc[header_row_idx])
        #     df = df[header_row_idx + 1:].reset_index(drop=True)
        # else:
        #     print(f"Warning: No clear header row found for Inter-Region table. Assuming first row is header.")
        #     df.columns = self._clean_column_names(df.iloc[0])
        #     df = df[1:].reset_index(drop=True)

        df['Import'] = None
        for i in range(df.shape[0]):
            if df.iloc[i].isna().sum() > 7:
                val = df.iloc[i,0]
            elif df.iloc[i].isna().sum() > 5:
                df.iloc[i] = [pd.NA, pd.NA, df.iloc[i,0], pd.NA, pd.NA, pd.NA, df.iloc[i,1], df.iloc[i,2], df.iloc[i,3], pd.NA]

            df.loc[i,'Import'] = val

        # Remove rows with more than 5 NaN values
        threshold = len(df.columns) - 5
        df = df.dropna(thresh=threshold)
            
        # Iterate through rows to find and forward-fill the import region group.
        # This requires checking the column where "ER-NR" etc. appears.
        # Assuming this is the first column after header cleanup, or an unnamed one.
        
        # # Check if the first column has a pattern like "XX-YY"
        # for i, row_vals in df.iterrows():
        #     if not row_vals.empty:
        #         first_col_val = str(row_vals.iloc[0]).strip()
        #         if re.match(r'[A-Z]{2}-[A-Z]{2}', first_col_val):
        #             df.loc[i, 'Import'] = first_col_val
        
        # df['Import'] = df['Import'].ffill()

        # line_details_col_name = None
        # for col in df.columns:
        #     if 'Line Details' in col:
        #         line_details_col_name = col
        #         break
        
        # if line_details_col_name:
        #     df_processed = df[~df[line_details_col_name].astype(str).str.contains('Total', na=False)].copy()
        #     # Also filter out rows that *are* the region headers (e.g., if "ER-NR" is in the 'Line Details' column due to shift)
        #     # Filter rows where the 'Import' column (now filled) is also present in 'Line Details' (indicating a header row)
        #     df_processed = df_processed[~df_processed.apply(lambda row: str(row['Import']) in str(row[line_details_col_name]), axis=1)].copy()

        # else:
        #     print("Warning: 'Line Details' column not found for Inter-Region table. Cannot filter totals/headers.")
        #     df_processed = df.copy()

        # Define CSV target columns
        df = df.iloc[:,1:]
        target_csv_cols = ['Voltage Level', 'Line Details', 'No. of Circuit', 'Max Import (MW)', 'Max Export (MW)', 'Import (MU)', 'Export (MU)', 'NET Import (MU)', 'Import']
        df.columns = target_csv_cols

        # # Map raw column names to target CSV names
        # column_remapping = {
        #     # Use actual column names from raw_df.columns that map to target_csv_cols
        #     'Voltage Level': 'Voltage Level',
        #     'Line Details': 'Line Details',
        #     'No. of Circuit': 'No. of Circuit',
        #     'Max Import (MW)': 'Max Import (MW)',
        #     'Max Export (MW)': 'Max Export (MW)',
        #     'Import (MU)': 'Import (MU)',
        #     'Export (MU)': 'Export (MU)',
        #     'NET Import (MU)': 'NET Import (MU)'
        # }
        # df_processed.rename(columns={k: v for k, v in column_remapping.items() if k in df_processed.columns}, inplace=True)
        
        # for col in target_csv_cols:
        #     if col not in df_processed.columns:
        #         df_processed[col] = None

        numeric_cols = ['No. of Circuit', 'Max Import (MW)', 'Max Export (MW)', 'Import (MU)', 'Export (MU)', 'NET Import (MU)']
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')
        
        df = self._add_common_cols(df, 'Inter-Region')
        
        final_df = df[['Date', 'Table Name', target_csv_cols[-1]] + target_csv_cols[:-1]]
        return final_df


    def transform_international_exchange(self, raw_df):
        """
        Transforms the raw DataFrame from 'International Exchange' (Page 3)
        into the 'International' table format of the CSV.
        Addressing: "BHUTAN India Total" rows.
        """
        df = raw_df.copy()
        df.columns = df.iloc[0]
        df = df[1:].reset_index(drop=True)

        # # Identify header row. This table often has text above the actual header that tabula picks up.
        # # Look for 'State', 'Region', 'Line Name'
        # header_row_idx = -1
        # for r_idx in range(min(df.shape[0], 3)):
        #     row_str = " ".join(df.iloc[r_idx].astype(str).fillna('').tolist())
        #     if "State" in row_str and "Region" in row_str and "Line Name" in row_str:
        #         header_row_idx = r_idx
        #         break
        
        # if header_row_idx != -1:
        #     df.columns = self._clean_column_names(df.iloc[header_row_idx])
        #     df = df[header_row_idx + 1:].reset_index(drop=True)
        # else:
        #     print(f"Warning: No clear header row found for International Exchange table. Assuming first row is header.")
        #     df.columns = self._clean_column_names(df.iloc[0])
        #     df = df[1:].reset_index(drop=True)
        idx = df.index[df['State'].str.contains('ER', na=False)]

        for i in idx:
            df.iloc[i,:] = df.iloc[i,:].shift(1, fill_value=pd.NA)

        # row_str = " ".join(df.iloc[0].astype(str).fillna('').tolist())
        # if "State" in row_str and "Region" in row_str and "Line Name" in row_str:
        #     df.columns = self._clean_column_names(df.iloc[0])
        #     df = df[1:].reset_index(drop=True)
        # else:
        #     print(f"Warning: No clear header row found for International Exchange table. Assuming first row is header.")
        #     df.columns = self._clean_column_names(df.iloc[0])
        #     df = df[1:].reset_index(drop=True)
        # Forward fill 'State' and 'Region'
        # Assuming cleaned headers are now 'State' and 'Region'
        if 'State' in df.columns:
            df['State'] = df['State'].replace('', pd.NA).ffill()
        if 'Region' in df.columns:
            df['Region'] = df['Region'].replace('', pd.NA).ffill()

        # # Filter out "Total" rows
        # if 'State' in df.columns: # Check if column exists after potential renaming
        #     df_filtered = df[~df['State'].astype(str).str.contains('Total', na=False)].copy()
        # else:
        #     print("Warning: 'State' column not found for International Exchange table. Cannot filter totals.")
        #     df_filtered = df.copy()

        # Define CSV target columns
        target_cols_final = ['State', 'Region', 'Line Name', 'Max (MW)', 'Min (MW)', 'Avg (MW)', 'Energy Exchange (MU)']
        df.columns = target_cols_final

        # # Map raw column names to target CSV names if they are different
        # column_remapping = {
        #     'Line Name': 'Line Name',
        #     'Max (MW)': 'Max (MW)', # Or 'Max MW)' if tabula renames
        #     'Min (MW)': 'Min (MW)',
        #     'Avg (MW)': 'Avg (MW)',
        #     'Energy Exchange (MU)': 'Energy Exchange (MU)'
        # }
        # df_processed = df_filtered.rename(columns={k: v for k, v in column_remapping.items() if k in df_filtered.columns})
        
        # for col in target_cols_final:
        #     if col not in df_processed.columns:
        #         df_processed[col] = None

        # df_processed = df_processed[target_cols_final].copy()

        numeric_cols = ['Max (MW)', 'Min (MW)', 'Avg (MW)', 'Energy Exchange (MU)']
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')

        df = self._add_common_cols(df, 'International')
        
        final_df = df[['Date', 'Table Name', 'State', 'Region', 'Line Name', 'Max (MW)', 'Min (MW)', 'Avg (MW)', 'Energy Exchange (MU)']]
        return final_df

    def transform_exchange(self, raw_df_export, raw_df_import, raw_df_net):
        """
        Transforms the raw DataFrames from CROSS BORDER EXCHANGE SCHEDULE (Export, Import, Net)
        into the 'Excchange' table format of the CSV.
        """
        all_exchange_dfs = []

        def process_single_exchange_table(df, exchange_type):
            df_processed = df.copy()
            df_processed = df_processed.iloc[3:, :]
            print(df_processed)

            # Identify header row for these tables (e.g., 'Country', '(ISGS/PPA)', 'BILATERAL', ...)
            # header_row_idx = 0
            # for r_idx in range(min(df_processed.shape[0], 3)):
            #     row_str = " ".join(df_processed.iloc[r_idx].astype(str).fillna('').tolist())
            #     if "Country" in row_str and "IEX" in row_str and "TOTAL" in row_str:
            #         header_row_idx = r_idx
            #         break
            
            # if header_row_idx != -1:
            #     df_processed.columns = self._clean_column_names(df_processed.iloc[header_row_idx])
            #     df_processed = df_processed[header_row_idx + 1:].reset_index(drop=True)
            # else:
            #     print(f"Warning: No clear header row found for {exchange_type} Exchange table. Assuming first row is header.")
            #     df_processed.columns = self._clean_column_names(df_processed.iloc[0])
            #     df_processed = df_processed[1:].reset_index(drop=True)

            # column_mapping = {
            #     'Country': 'Country',
            #     '(ISGS/PPA)': 'PPA',
            #     'BILATERAL': 'Bilateral', # Or 'BILATERAL TOTAL'
            #     'IEX': 'DAM IEX',
            #     'PXIL': 'DAM PXIL',
            #     'HPX': 'DAM HPX',
            #     'IEX.1': 'RTM IEX', # If tabula names second IEX as IEX.1
            #     'PXIL.1': 'RTM PXIL',
            #     'HPX.1': 'RTM HPX',
            #     'Total': 'Total',
            #     'DAM': 'DAM', # If these are separate columns for DAM and RTM groups
            #     'RTM': 'RTM'
            # }
            
            # df_processed.rename(columns={k: v for k, v in column_mapping.items() if k in df_processed.columns}, inplace=True)
            
            # Filter rows that are "Total Export", "Total Import", "Total Net"
            # df_processed = df_processed[~df_processed['Country'].astype(str).str.contains('Total', na=False)].copy()
            raw_cols = ['Country', 'PPA', 'Bilateral', 'DAM IEX', 'DAM PXIL', 'DAM HPX', 'RTM IEX', 'RTM PXIL', 'RTM HPX', 'Total']
            if df_processed.shape[1] == len(raw_cols):
                df_processed.columns = raw_cols
            else:
                print(f"Warning: Mismatch in number of columns for {exchange_type} Exchange table.")
                return(0)

            df_processed['Type'] = exchange_type
            df_processed = self._add_common_cols(df_processed, 'Excchange')
            df_processed = df_processed[['Date', 'Table Name', 'Type', 'Country', 'PPA', 'Bilateral', 'DAM IEX', 'DAM PXIL', 'DAM HPX', 'RTM IEX', 'RTM PXIL', 'RTM HPX', 'Total']]

            
            # for col in numeric_cols:
            #     if col in df_processed.columns:
            #         df_processed[col] = pd.to_numeric(df_processed[col], errors='coerce')
            return df_processed

        all_exchange_dfs.append(process_single_exchange_table(raw_df_export, 'Export'))
        all_exchange_dfs.append(process_single_exchange_table(raw_df_import, 'Import'))
        all_exchange_dfs.append(process_single_exchange_table(raw_df_net, 'NET'))

        combined_df = pd.concat([df for df in all_exchange_dfs if not df.empty], ignore_index=True)
        final_cols = ['Date', 'Table Name', 'Type', 'Country', 'PPA', 'Bilateral', 'DAM IEX', 'DAM PXIL',
                      'DAM HPX', 'RTM IEX', 'RTM PXIL', 'RTM HPX', 'Total']
        
        if combined_df.shape[1] == len(final_cols):
            combined_df.columns = final_cols
        else:
            print(f"Warning: Mismatch in number of columns for Exchange table.")
            return(0)

        numeric_cols = ['PPA', 'Bilateral', 'DAM IEX', 'DAM PXIL', 'DAM HPX', 'RTM IEX', 'RTM PXIL', 'RTM HPX', 'Total']
        for col in numeric_cols:
            if col in combined_df.columns:
                combined_df[col] = pd.to_numeric(combined_df[col], errors='coerce')
        
        # for col in final_cols:
        #     if col not in combined_df.columns:
        #         combined_df[col] = None
        
        return combined_df[final_cols]


    def transform_block_wise(self, raw_df):
        """
        Transforms the raw DataFrame from '15 Min (INSTANTANEOUS) ALL INDIA GRID FREQUENCY...' (Page 5)
        into the 'Block-wise' table format of the CSV.
        """
        df = raw_df.copy()
        
        # Identify the complex header rows. This table usually has 2-3 rows forming the header.
        # Look for keywords like 'TIME', 'FREQUENCY', 'DEMAND MET', 'NUCLEAR'
        header_row_start_idx = -1
        for r_idx in range(min(df.shape[0], 5)): # Check first few rows
            row_str = " ".join(df.iloc[r_idx].astype(str).fillna('').tolist())
            if "TIME" in row_str and "FREQUENCY" in row_str and "DEMAND MET" in row_str:
                header_row_start_idx = r_idx
                break
        
        if header_row_start_idx != -1:
            # Need to combine potentially two rows for headers
            # Assuming row 'header_row_start_idx' contains 'TIME', 'FREQUENCY (Hz)'
            # And row 'header_row_start_idx + 1' contains 'DEMAND MET (MW)', 'NUCLEAR (MW)' etc.
            # We need to construct new header names from these two rows.
            
            if header_row_start_idx + 1 < df.shape[0]:
                top_header = df.iloc[header_row_start_idx].astype(str).fillna('')
                bottom_header = df.iloc[header_row_start_idx + 1].astype(str).fillna('')
                
                new_columns = []
                for i in range(len(top_header)):
                    combined_name = bottom_header[i].strip()
                    if top_header[i].strip() and top_header[i].strip() != combined_name:
                         # Combine if top header is not empty and different from bottom.
                         # This handles cases like 'NET TRANSNATIONAL EXCHANGE' spanning.
                        combined_name = f"{top_header[i].strip()} {combined_name}"
                    
                    new_columns.append(combined_name)
                
                df.columns = self._clean_column_names(new_columns)
                df = df[header_row_start_idx + 2:].reset_index(drop=True) # Data starts after these two rows
            else:
                # Only one header row, assume it's simple
                df.columns = self._clean_column_names(df.iloc[header_row_start_idx])
                df = df[header_row_start_idx + 1:].reset_index(drop=True)
        else:
            print(f"Warning: No clear header row found for Block-wise table. Assuming first row is header.")
            df.columns = self._clean_column_names(df.iloc[0])
            df = df[1:].reset_index(drop=True)
            
        # Specific remapping for cleaned headers to final CSV names
        column_mapping = {
            'TIME': 'TIME',
            'FREQUENCY (Hz)': 'FREQUENCY (Hz)',
            'DEMAND MET (MW)': 'DEMAND MET (MW)',
            'NUCLEAR (MW)': 'NUCLEAR (MW)',
            'WIND (MW)': 'WIND (MW)',
            'SOLAR (MW)': 'SOLAR (MW)',
            'HYDRO (MW)': 'HYDRO (MW)',
            'GAS (MW)': 'GAS (MW)',
            'THERMAL (MW)': 'THERMAL (MW)',
            'OTHERS* (MW)': 'OTHERS* (MW)',
            'NET DEMAND MET (MW)': 'NET DEMAND MET (MW)',
            'TOTAL GENERATION (MW)': 'TOTAL GENERATION (MW)',
            'NET TRANSNATIONAL EXCHANGE (MW) (+ve) Import, (-ve) Export': 'NET TRANSNATIONAL EXCHANGE (MW) (+ve) Import, (-ve) Export'
        }
        
        df.rename(columns={k: v for k, v in column_mapping.items() if k in df.columns}, inplace=True)

        numeric_cols = [
            'FREQUENCY (Hz)', 'DEMAND MET (MW)', 'NUCLEAR (MW)', 'WIND (MW)', 'SOLAR (MW)',
            'HYDRO (MW)', 'GAS (MW)', 'THERMAL (MW)', 'OTHERS* (MW)', 'NET DEMAND MET (MW)',
            'TOTAL GENERATION (MW)', 'NET TRANSNATIONAL EXCHANGE (MW) (+ve) Import, (-ve) Export'
        ]
        for col in numeric_cols:
            if col in df.columns:
                df[col] = df[col].astype(str).str.replace(',', '').str.strip()
                df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

        df = self._add_common_cols(df, 'Block-wise')

        final_cols = ['Date', 'Table Name', 'TIME', 'FREQUENCY (Hz)', 'DEMAND MET (MW)', 'NUCLEAR (MW)',
                      'WIND (MW)', 'SOLAR (MW)', 'HYDRO (MW)', 'GAS (MW)', 'THERMAL (MW)',
                      'OTHERS* (MW)', 'NET DEMAND MET (MW)', 'TOTAL GENERATION (MW)',
                      'NET TRANSNATIONAL EXCHANGE (MW) (+ve) Import, (-ve) Export']
        
        for col in final_cols:
            if col not in df.columns:
                df[col] = None
        
        return df[final_cols]


# --- Main Orchestrator ---

def main_process():
    print("Starting the main PDF parsing process...")
    raw_tables_dict, report_date = extract_and_process_tables()
    
    identified_tables = identify_and_preprocess_raw_tables(raw_tables_dict)
    for key, value in identified_tables.items():
        print(f"{key}: {identified_tables[key].columns}")

    transformer = PSPTransformer(report_date)
    
    final_dfs_list = []

    # Process each identified table using the transformer
    # Ensure all required raw DFs are present before calling complex transformations
    if 'A. Power Supply Position at All India and Regional level' in identified_tables and \
       'B. Frequency Profile (%)' in identified_tables and \
       'E. Import/Export by Regions (in MU) - Import(+ve)/Export(-ve); OD(+)/UD(-)' in identified_tables and \
       'F. Generation Outage(MW)' in identified_tables and \
       'G. Sourcewise generation (Gross) (MU)' in identified_tables and \
       'G. Share of RE and Non-fossil' in identified_tables and \
       'H. All India Demand Diversity Factor' in identified_tables and \
       'I. All India Peak Demand and shortage at Solar and Non-Solar Hour' in identified_tables:
        
        df_regional = transformer.transform_regional_summary(
            identified_tables['A. Power Supply Position at All India and Regional level'],
            identified_tables['B. Frequency Profile (%)'],
            identified_tables['E. Import/Export by Regions (in MU) - Import(+ve)/Export(-ve); OD(+)/UD(-)'],
            identified_tables['F. Generation Outage(MW)'],
            identified_tables['G. Sourcewise generation (Gross) (MU)'],
            identified_tables['G. Share of RE and Non-fossil'],
            identified_tables['H. All India Demand Diversity Factor'],
            identified_tables['I. All India Peak Demand and shortage at Solar and Non-Solar Hour']
        )
        if not df_regional.empty:
            final_dfs_list.append(df_regional)
    else:
        print("Skipping Regional Summary transformation due to missing source tables.")

    if 'C. Power Supply Position in States' in identified_tables:
        df_states = transformer.transform_states(identified_tables['C. Power Supply Position in States'])
        if not df_states.empty:
            final_dfs_list.append(df_states)
    else:
        print("Skipping States transformation due to missing source table.")
    
    if 'D. Transnational Exchanges (MU) - Import(+ve)/Export(-ve)' in identified_tables:
        df_international_net = transformer.transform_international_net(identified_tables['D. Transnational Exchanges (MU) - Import(+ve)/Export(-ve)'])
        if not df_international_net.empty:
            final_dfs_list.append(df_international_net)
    else:
        print("Skipping International NET transformation due to missing source table.")

    if 'Intra-national Exchange' in identified_tables:
        df_inter_region = transformer.transform_inter_region(identified_tables['Intra-national Exchange'])
        if not df_inter_region.empty:
            final_dfs_list.append(df_inter_region)
    else:
        print("Skipping Inter-Region transformation due to missing source table.")

    if 'International Exchange' in identified_tables:
        df_international = transformer.transform_international_exchange(identified_tables['International Exchange'])
        if not df_international.empty:
            final_dfs_list.append(df_international)
    else:
        print("Skipping International Exchange transformation due to missing source table.")

    if 'Export From India (in MU)' in identified_tables and \
       'Import by India(in MU)' in identified_tables and \
       'Net from India(in MU)' in identified_tables:
        df_exchange = transformer.transform_exchange(
            identified_tables['Export From India (in MU)'],
            identified_tables['Import by India(in MU)'],
            identified_tables['Net from India(in MU)']
        )
        if not df_exchange.empty:
            final_dfs_list.append(df_exchange)
    else:
        print("Skipping Excchange transformation due to missing source tables.")

    if '15 Min (INSTANTANEOUS) ALL INDIA GRID FREQUENCY, GENERATION & DEMAND MET (SCADA DATA)' in identified_tables:
        df_block_wise = transformer.transform_block_wise(identified_tables['15 Min (INSTANTANEOUS) ALL INDIA GRID FREQUENCY, GENERATION & DEMAND MET (SCADA DATA)'])
        if not df_block_wise.empty:
            final_dfs_list.append(df_block_wise)
    else:
        print("Skipping Block-wise transformation due to missing source table.")

    # if final_dfs_list:
    #     final_combined_df = pd.concat(final_dfs_list, ignore_index=True)
    #     # Optional: Save to CSV
    #     output_dir = "sample output"
    #     os.makedirs(output_dir, exist_ok=True)
    #     output_path = os.path.join(output_dir, "Processed_PSP_from_Tabula.csv")
    #     final_combined_df.to_csv(output_path, index=False)
    #     print(f"Combined data saved to {output_path}")
    #     return final_combined_df
    # else:
    #     print("No tables were processed for final combination.")
    #     return pd.DataFrame()
    return final_dfs_list

# Call the main function to run the process
if __name__ == "__main__":
    processed_data = main_process()
    # print("\n--- Final Processed Data (Head) ---")
    # print(processed_data.head(20)) # Print more rows to see different table types
    # print("\n--- Final Processed Data (Info) ---")
    # print(processed_data.info())
    # print("\n--- Value Counts for 'Table Name' ---")
    # print(processed_data['Table Name'].value_counts())

    # Keep the console open
    import code
    code.interact(local=locals())  
