import tabula
import pandas as pd
import os
from PyPDF2 import PdfReader
from datetime import datetime
import re
import logging

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# --- Stage 1: Data Extraction using tabula-py ---

def _get_report_date_from_pdf(pdf_path):
    """
    Extracts the report date from the first page of the PDF.
    Searches for a specific pattern 'for the date DD.MM.YYYY'.
    Converts the extracted date to 'M/D/YYYY' format.

    Args:
        pdf_path (str): The file path to the PDF document.

    Returns:
        str: The extracted date in 'M/D/YYYY' format, or "Unknown Date" if not found or on error.
    """
    try:
        reader = PdfReader(pdf_path)
        first_page_text = reader.pages[0].extract_text()
        # Search for the date pattern (e.g., "for the date 19.04.2025")
        match = re.search(r"for the date (\d{2}\.\d{2}\.\d{4})", first_page_text)
        if match:
            date_str_ddmmyyyy = match.group(1)
            # Convert DD.MM.YYYY to M/D/YYYY
            day, month, year = date_str_ddmmyyyy.split('.')
            return f"{int(month)}/{int(day)}/{year}"
        print("Warning: Could not find report date in PDF.")
        return "Unknown Date"  # Return a default if date pattern not found
    except Exception as e:
        print(f"Error extracting report date: {e}")
        return "Unknown Date"  # Return a default on any exception

def extract_and_process_tables(pdf_path):
    """
    Extracts all tables from all pages of a specified PDF using tabula-py.
    Also retrieves the report date from the PDF.

    Args:
        pdf_path (str): The file path to the PDF document.

    Returns:
        tuple: A tuple containing:
            - processed_tables (dict): Keys are 'page_X_table_Y', values are raw pandas DataFrames.
            - report_date (str): The extracted report date.
    """
    # pdf_path = "sample input/18.04.25_NLDC_PSP.pdf"  # Hardcoded PDF path
    try:
        reader = PdfReader(pdf_path)
        num_pages = len(reader.pages)
    except Exception as e:
        print(f"Error reading PDF for page count: {e}")
        return {}, "Unknown Date" # Return empty if PDF can't be read

    processed_tables = {}
    print(f"Processing {num_pages} pages...")
    report_date = _get_report_date_from_pdf(pdf_path)

    # Iterate through each page to extract tables
    # tabula pages are 1-indexed
    for page_num in range(1, num_pages + 1):
        try:
            # tabula.read_pdf is the core extraction function.
            # Parameters like guess=True, lattice=True, stream=True are used to maximize table detection.
            tables_on_page = tabula.read_pdf(
                pdf_path,
                pages=page_num,
                multiple_tables=True,
                guess=True,      # Allows tabula to guess table areas, can be less precise but more comprehensive
                lattice=True,    # Assumes clear lines define table cells
                stream=True,     # Useful for tables without clear lines, uses whitespace
                silent=True      # Suppress tabula's command line output for cleaner logs
            )

            # Store each extracted table with a unique key
            for table_idx, table_df in enumerate(tables_on_page):
                if isinstance(table_df, pd.DataFrame): # Ensure tabula returned a DataFrame
                    processed_tables[f"page_{page_num}_table_{table_idx}"] = table_df
            print(f"Processed page {page_num}. Found {len(tables_on_page)} table(s).")

        except Exception as e:
            # Log errors per page, allowing other pages to process
            print(f"Error processing page {page_num}: {str(e)}")

    return processed_tables, report_date

# --- Stage 2: Identifying and Pre-processing Raw Tables ---

def identify_and_preprocess_raw_tables(raw_tables_dict):
    """
    Maps raw DataFrames from tabula's output to logical table names.
    Performs generic cleanup (dropping fully empty rows/columns).
    Header processing is deferred to specific transformation functions.

    Args:
        raw_tables_dict (dict): Dictionary of raw DataFrames from extract_and_process_tables.

    Returns:
        dict: Dictionary where keys are logical table names and values are the preprocessed DataFrames.
    """
    identified_tables = {}

    # CRITICAL: This map links tabula's output keys (e.g., 'page_2_table_0')
    # to meaningful logical table names. It MUST be updated based on the
    # actual keys generated by `extract_and_process_tables()` for a given PDF.
    # To get these keys, run: print(raw_tables_dict.keys()) after extraction.
    table_key_to_logical_name_map = {
        'page_2_table_0': 'A. Power Supply Position at All India and Regional level',
        'page_2_table_1': 'B. Frequency Profile (%)',
        'page_2_table_2': 'C. Power Supply Position in States',
        'page_2_table_3': 'D. Transnational Exchanges (MU) - Import(+ve)/Export(-ve)',
        'page_2_table_4': 'E. Import/Export by Regions (in MU) - Import(+ve)/Export(-ve); OD(+)/UD(-)',
        'page_2_table_5': 'F. Generation Outage(MW)',
        'page_2_table_6': 'G. Sourcewise generation (Gross) (MU)',
        'page_2_table_7': 'G. Share of RE and Non-fossil',
        'page_2_table_8': 'H. All India Demand Diversity Factor',
        'page_2_table_9': 'I. All India Peak Demand and shortage at Solar and Non-Solar Hour',
        'page_3_table_0': 'Intra-national Exchange',
        'page_3_table_1': 'International Exchange',
        'page_4_table_0': 'Export From India (in MU)',
        'page_4_table_1': 'Import by India(in MU)',
        'page_4_table_2': 'Net from India(in MU)',
        'page_5_table_0': '15 Min (INSTANTANEOUS) ALL INDIA GRID FREQUENCY, GENERATION & DEMAND MET (SCADA DATA)',
        'page_1_table_0': 'GARBAGE_TO_SKIP' # Example for skipping an irrelevant table
    }

    for tabula_key, df in raw_tables_dict.items():
        logical_name = table_key_to_logical_name_map.get(tabula_key)

        if logical_name and logical_name != 'GARBAGE_TO_SKIP':
            # DataFrames are passed as-is from tabula.
            # Specific header processing will happen in transform_ methods.
            
            # Perform generic cleanup: remove rows/columns that are entirely empty.
            # This is useful as tabula can sometimes create these artifacts.
            if not df.empty:
                df_cleaned = df.dropna(axis=1, how='all').dropna(axis=0, how='all')
                if not df_cleaned.empty: # Ensure DataFrame is not empty after cleanup
                    identified_tables[logical_name] = df_cleaned
                    print(f"Identified table: '{logical_name}' from raw key: {tabula_key}")
                else:
                    print(f"Table from raw key {tabula_key} ('{logical_name}') became empty after cleanup. Skipping.")
            else:
                print(f"Raw table from key {tabula_key} ('{logical_name}') is empty. Skipping.")

        elif logical_name == 'GARBAGE_TO_SKIP':
            print(f"Skipping garbage table: {tabula_key}")
        else:
            # Warn if a table extracted by tabula doesn't have a mapping.
            # This might indicate a new/unexpected table or an incomplete map.
            print(f"No specific mapping found for raw key: {tabula_key}. Contents: \n{df.head(2)}\nSkipping or consider adding to map.")

    print(f"Identified {len(identified_tables)} key tables for transformation.")
    return identified_tables

# --- Stage 3: Data Transformation Functions (Adjusted for raw input) ---

# --- PSPTransformer Class (Modified based on corrections) ---

class PSPTransformer:
    def __init__(self, report_date):
        self.report_date = report_date

    def _clean_column_names(self, df_columns):
        cleaned_cols = []
        for col in df_columns:
            cleaned_col = str(col).strip().replace('\n', ' ', -1)
            cleaned_col = cleaned_col.replace('*', '', -1).replace('(', '', -1).replace(')', '', -1)
            cleaned_cols.append(cleaned_col)
        return cleaned_cols

    def _add_common_cols(self, df, table_name):
        df_out = df.copy()
        df_out['Date'] = self.report_date
        df_out['Table Name'] = table_name # Corrected from 'Excchange' if it was specific to one call
        return df_out

    def transform_states(self, raw_df):
        df = raw_df.copy()
        target_csv_columns = [
            'Region', 'States', 'Maximum Demand (MW)', 'Shortage (MW)', 'Energy Met (MU)',
            'Drawal Schedule (MU)', 'OD(+)/UD(-) (MU)', 'Max OD (MW)', 'Energy Shortage (MU)'
        ]

        if df.shape[1] != len(target_csv_columns):
            raise ValueError(
                f"Error (States Table): Column count mismatch. "
                f"Expected {len(target_csv_columns)}, got {df.shape[1]}."
            )
        df.columns = target_csv_columns

        # Convert numeric columns to float64 at the start
        numeric_cols = [
            'Maximum Demand (MW)', 'Shortage (MW)', 'Energy Met (MU)',
            'Drawal Schedule (MU)', 'OD(+)/UD(-) (MU)', 'Max OD (MW)', 'Energy Shortage (MU)'
        ]
        for col in numeric_cols:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce').astype('float64')

        if 'Region' in df.columns:
            region_codes = ['NR', 'WR', 'SR', 'ER', 'NER', 'ALL INDIA']
            mask = (~df['Region'].isin(region_codes)) & (df['Region'].notna())
            idx = df.index[mask]
            
            for i in idx:
                # Get the row and shift it
                row = df.iloc[i].copy()
                shifted_values = row.shift(1, fill_value=pd.NA)
                
                # Assign values back maintaining dtypes
                for col in df.columns:
                    if col in numeric_cols:
                        # For numeric columns, ensure float64
                        df.at[i, col] = pd.to_numeric(shifted_values[col], errors='coerce')
                    else:
                        # For non-numeric columns (Region, States), keep as is
                        df.at[i, col] = shifted_values[col]

        region_mapping = {
            'Punjab': 'NR', 'Haryana': 'NR', 'Rajasthan': 'NR', 'Delhi': 'NR', 'UP': 'NR',
            'Uttarakhand': 'NR', 'HP': 'NR', 'J&K(UT) & Ladakh(UT)': 'NR', 'Chandigarh': 'NR', 'Railways_NR ISTS': 'NR',
            'Chhattisgarh': 'WR', 'Gujarat': 'WR', 'MP': 'WR', 'Maharashtra': 'WR', 'Goa': 'WR',
            'DNHDDPDCL': 'WR', 'AMNSIL': 'WR', 'BALCO': 'WR', 'RIL JAMNAGAR': 'WR',
            'Andhra Pradesh': 'SR', 'Telangana': 'SR', 'Karnataka': 'SR', 'Kerala': 'SR', 'Tamil Nadu': 'SR', 'Puducherry': 'SR',
            'Bihar': 'ER', 'DVC': 'ER', 'Jharkhand': 'ER', 'Odisha': 'ER', 'West Bengal': 'ER', 'Sikkim': 'ER', 'Railways_ER ISTS': 'ER',
            'Arunachal Pradesh': 'NER', 'Assam': 'NER', 'Manipur': 'NER', 'Meghalaya': 'NER', 'Mizoram': 'NER', 'Nagaland': 'NER', 'Tripura': 'NER'
        }
        
        if 'States' in df.columns and 'Region' in df.columns:
            # Handle state mapping...
            unmapped_states = []
            for state in df['States'].dropna().astype(str).str.strip().unique():
                if state and state not in region_mapping:
                    if not any(summary_keyword in state.upper() for summary_keyword in ["TOTAL", "ALL INDIA"]):
                        unmapped_states.append(state)
            
            if unmapped_states:
                raise ValueError(
                    f"Error (States Table): Unmapped states found: {', '.join(unmapped_states)}."
                )

            df['Region'] = df.apply(lambda row: region_mapping.get(str(row['States']).strip(), row['Region']), axis=1)
            df['Region'] = df['Region'].replace('', pd.NA).ffill()
        else:
            raise ValueError("Error (States Table): 'States' or 'Region' column not found for mapping.")

        # Clean and convert numeric columns one final time
        for col in numeric_cols:
            if col in df.columns:
                # Remove commas and clean up decimal points
                df[col] = df[col].astype(str).str.replace(',', '', regex=False).str.strip()
                df[col] = df[col].str.replace(r'\.+', '.', regex=True).str.rstrip('.')
                # Convert to float64
                df[col] = pd.to_numeric(df[col], errors='coerce').astype('float64')

        df = self._add_common_cols(df, 'States')
        final_ordered_columns = ['Date', 'Table Name'] + target_csv_columns
        return df[final_ordered_columns]

    def transform_international_net(self, raw_df):
        df = raw_df.copy()

        # Correction: Raw table from tabula should have 2 rows and 5 columns.
        expected_rows, expected_cols_raw = 2, 5
        if not (df.shape[0] == expected_rows and df.shape[1] == expected_cols_raw):
            raise ValueError(
                f"Error (International NET): Raw table shape mismatch. "
                f"Expected ({expected_rows} rows, {expected_cols_raw} cols), got {df.shape}. "
                f"Check PDF structure or tabula extraction."
            )
        
        # Values from 2nd to 5th column (index 1 to 4) for both rows
        numeric_list = df.iloc[0, 1:expected_cols_raw].tolist() + df.iloc[1, 1:expected_cols_raw].tolist()

        target_columns = [ # 8 target columns
            'Bhutan (MU)', 'Nepal (MU)', 'Bangladesh(MU)', 'Godda (Bangladesh) (MU)', 
            'Bhutan Peak (MW)', 'Nepal Peak (MW)', 'Bangladesh Peak (MW)', 'Godda (Bangladesh) Peak (MW)'
        ]
        
        if len(numeric_list) != len(target_columns):
            # This should not happen if raw table shape is (2,5) and numeric_list extraction is correct (4+4=8)
            raise ValueError(
                f"Error (International NET): Mismatch between extracted values ({len(numeric_list)}) "
                f"and target columns ({len(target_columns)}). Logic error in numeric_list creation."
            )
        
        df_processed = pd.DataFrame([numeric_list], columns=target_columns)
        
        for col in target_columns:
            df_processed[col] = pd.to_numeric(df_processed[col], errors='coerce')
        
        df_processed = self._add_common_cols(df_processed, 'International NET')
        
        final_ordered_columns = ['Date', 'Table Name'] + target_columns
        # Correction: Final processed table must have all columns as in final_ordered_columns.
        if not all(col in df_processed.columns for col in final_ordered_columns) or \
           len(df_processed.columns) != len(final_ordered_columns):
            # This check is somewhat redundant if df_processed is built correctly above.
            raise ValueError(
                f"Error (International NET): Final processed table columns mismatch. "
                f"Expected {len(final_ordered_columns)} columns: {final_ordered_columns}, "
                f"Got {len(df_processed.columns)} columns: {df_processed.columns.tolist()}."
            )
        return df_processed[final_ordered_columns]


    def transform_regional_summary(self, raw_df_A, raw_df_B, raw_df_E, raw_df_F, raw_df_G_main, raw_df_G_share, raw_df_H, raw_df_I):
        melted_data_list = []
        
        # --- Pre-process G_Main to get its cleaned column structure for G_Share ---
        df_g_main_for_cols = raw_df_G_main.copy()
        if df_g_main_for_cols.empty:
            raise ValueError("Error (Regional Summary - G_Main for G_Share): raw_df_G_main is empty, cannot proceed.")
        
        # Assuming G_Main's first row (if multi-row header) or its columns (if single/no header) are relevant
        # For simplicity, let's assume tabula's output columns for G_Main are somewhat usable or need cleaning.
        # This relies on _clean_column_names being robust for G_Main's header structure.
        # A more robust dynamic header finding for G_Main would be ideal here.
        # For now, clean whatever columns raw_df_G_main has.
        cleaned_g_main_cols = self._clean_column_names(df_g_main_for_cols.columns)


        # --- Process G_Share using G_Main's column structure (Correction) ---
        df_g_share_copy = raw_df_G_share.copy()
        if df_g_share_copy.empty:
            raise ValueError("Error (Regional Summary - G_Share): raw_df_G_share is empty.")

        # Store original columns of G_Share (which tabula might have taken from its first data row)
        original_g_share_header_as_data = df_g_share_copy.columns.tolist()
        
        # Create a new DataFrame for G_Share starting with its "original header" as the first data row
        df_g_share_transformed = pd.DataFrame([original_g_share_header_as_data], columns=cleaned_g_main_cols[:len(original_g_share_header_as_data)])
        
        # Append the rest of G_Share's data
        # The raw G_Share data (excluding its original first row which became header) needs to be re-aligned under new columns
        # This assumes df_g_share_copy's data rows have the same width as original_g_share_header_as_data
        if df_g_share_copy.shape[0] > 0 : # If there was data beyond the first row interpreted as header
            g_share_data_df = pd.DataFrame(data=df_g_share_copy.values, columns=cleaned_g_main_cols[:df_g_share_copy.shape[1]])
            df_g_share_transformed = pd.concat([df_g_share_transformed, g_share_data_df], ignore_index=True)
        
        # Now df_g_share_transformed has G_Main's column names (partially) and its first row is the original "header" data.
        # Proceed to melt it.
        if df_g_share_transformed.shape[1] >= 2:
            g_share_metrics_col = df_g_share_transformed.columns[0]
            g_share_region_cols = df_g_share_transformed.columns[1:]
            df_g_share_melted = df_g_share_transformed.melt(
                id_vars=[g_share_metrics_col], value_vars=g_share_region_cols,
                var_name='Region', value_name='Value'
            )
            df_g_share_melted.rename(columns={g_share_metrics_col: 'Metric'}, inplace=True)
            df_g_share_melted['Region'] = df_g_share_melted['Region'].astype(str).str.strip().replace(
                {'TOTAL': 'India', 'All India': 'India', '% Share': 'India'}, regex=False
            )
            melted_data_list.append(df_g_share_melted[['Metric', 'Region', 'Value']])
        else:
            raise ValueError("Error (Regional Summary - G_Share): Transformed G_Share table is not wide enough to melt after column assignment.")

        # --- Process Tables A, E, F, G_main (G_main is processed again for its own data) ---
        data_sources_for_melt = [
            (raw_df_A, 'A'), (raw_df_E, 'E'), (raw_df_F, 'F'), (raw_df_G_main, 'G_Main')
        ]
        for df_source, source_name in data_sources_for_melt:
            df_temp = df_source.copy()
            if df_temp.empty or df_temp.shape[1] < 2:
                raise ValueError(f"Error (Regional Summary - {source_name}): Source table is empty or has < 2 columns.")
            
            df_temp.columns = self._clean_column_names(df_temp.columns) # Clean columns before melt
            metrics_col_name = df_temp.columns[0]
            region_col_names = df_temp.columns[1:]
            df_melted = df_temp.melt(
                id_vars=[metrics_col_name], value_vars=region_col_names,
                var_name='Region', value_name='Value'
            )
            df_melted.rename(columns={metrics_col_name: 'Metric'}, inplace=True)
            df_melted['Region'] = df_melted['Region'].astype(str).str.strip().replace(
                {'TOTAL': 'India', 'All India': 'India', '% Share': 'India'}, regex=False
            )
            melted_data_list.append(df_melted[['Metric', 'Region', 'Value']])

        combined_melted_df = pd.concat(melted_data_list, ignore_index=True)
        additional_rows = []

        # --- Process Table B: Frequency Profile (%) ---
        df_b = raw_df_B.copy()
        if df_b.empty:
            raise ValueError("Error (Regional Summary - B): Frequency Profile table is empty.")

        # Find the All India row
        all_india_mask = df_b.iloc[:, 0].astype(str).str.contains('All India', case=False, na=False)
        if not any(all_india_mask):
            raise ValueError("Error (Regional Summary - B): Could not find 'All India' row in Frequency Profile table.")

        all_india_row = df_b[all_india_mask].iloc[0]

        # Define the frequency metrics and their corresponding column indices
        freq_metrics = [
            ('FVI', 1),  # Assuming FVI is in the second column
            ('Frequency (<49.7)', 2),
            ('Frequency (49.7 - 49.8)', 3),
            ('Frequency (49.8 - 49.9)', 4),
            ('Frequency (< 49.9)', 5),
            ('Frequency (49.9 - 50.05)', 6),
            ('Frequency (> 50.05)', 7)
        ]

        # Add frequency profile data for India
        for metric_name, col_idx in freq_metrics:
            if col_idx < len(all_india_row):
                value = all_india_row.iloc[col_idx]
                # Convert to numeric, handling any non-numeric values
                try:
                    value = pd.to_numeric(str(value).replace('%', '').strip(), errors='coerce')
                except:
                    value = None
                
                combined_melted_df.loc[len(combined_melted_df)] = {
                    'Metric': metric_name,
                    'Region': 'India',
                    'Value': value
                }
            else:
                print(f"Warning: Column index {col_idx} out of range for frequency metric {metric_name}")

        # --- Process Table H: All India Demand Diversity Factor (Correction) ---
        df_h_copy = raw_df_H.copy()
        # Correction: Table H must have exactly two columns and one data row.
        # If tabula sets the header correctly, raw_df_H.shape[0] would be 1 (data)
        # and raw_df_H.shape[1] would be 2.
        if not (df_h_copy.shape[0] == 1 and df_h_copy.shape[1] == 2):
            raise ValueError(
                f"Error (Regional Summary - H): Table H shape mismatch. "
                f"Expected (1 row of data, 2 columns), got {df_h_copy.shape}. "
                f"Tabula output: columns={df_h_copy.columns.tolist()}, first data row={df_h_copy.iloc[0].tolist() if df_h_copy.shape[0]>=1 else 'N/A'}"
            )
        
        # 'Region DDF' value from the *name* of the second column.
        # 'States DDF' value from the first data row, second column.
        additional_rows.append({
            'Metric': 'Region DDF', 'Region': 'India', 'Value': str(df_h_copy.columns[1]) # Value is column name
        })
        additional_rows.append({
            'Metric': 'States DDF', 'Region': 'India', 'Value': df_h_copy.iloc[0, 1]     # Value is cell content
        })
        

        if additional_rows:
            df_additional_rows = pd.DataFrame(additional_rows)
            combined_melted_df = pd.concat([combined_melted_df, df_additional_rows], ignore_index=True)

        # --- Process Table I: All India Peak Demand and shortage ---
        # (Logic for table I processing - assuming it remains similar to previous, with appropriate error checks)
        # Correction: Raw table from tabula should have 2 rows and 5 columns.
        
        df_i_copy = raw_df_I
        expected_rows, expected_cols_raw = 2, 4
        if not (df_i_copy.shape[0] == expected_rows and df_i_copy.shape[1] == expected_cols_raw):
            raise ValueError(
                f"Error (International NET): Raw table shape mismatch. "
                f"Expected ({expected_rows} rows, {expected_cols_raw} cols), got {df_i_copy.shape}. "
                f"Check PDF structure or tabula extraction."
            )
        
        # Values from 2nd to 4th column (index 1 to 4) for both rows
        numeric_list = df_i_copy.iloc[0, 1:expected_cols_raw].tolist() + df_i_copy.iloc[1, 1:expected_cols_raw].tolist()

        target_columns = [ # 6 target columns
            'SolarHR Max Demand', 'SolarHR Max Demand Time', 'SolarHR Shortage',
              'Non-SolarHR Max Demand', 'Non-SolarHR Max Demand Time',	'Non-SolarHR Shortage'
        ]
        
        if len(numeric_list) != len(target_columns):
            # This should not happen if raw table shape is (2,4) and numeric_list extraction is correct (3+3=6)
            raise ValueError(
                f"Error (International NET): Mismatch between extracted values ({len(numeric_list)}) "
                f"and target columns ({len(target_columns)}). Logic error in numeric_list creation."
            )
        
        df_processed = pd.DataFrame([numeric_list], columns=target_columns)
        
        # Add Solar Hour and Non-Solar Hour data for India
        for metric_name in target_columns:
                         
            combined_melted_df.loc[len(combined_melted_df)] = {
                'Metric': metric_name,
                'Region': 'India',
                'Value': df_processed.loc[0, metric_name]
            }
            

        if combined_melted_df.empty:
            raise ValueError("Error (Regional Summary): No data to pivot after processing all sources.")
        
        original_metric_order = combined_melted_df['Metric'].drop_duplicates().tolist()
        pivoted_dfs_list = []
        # (Pivoting logic remains similar) ...
        for region_name in combined_melted_df['Region'].unique():
            df_region_specific = combined_melted_df[combined_melted_df['Region'] == region_name]
            df_pivoted = df_region_specific.pivot_table(
                index='Region', columns='Metric', values='Value', aggfunc='first'
            ).reset_index()
            df_pivoted.rename(columns={'Region': 'Table Name'}, inplace=True)
            df_pivoted['Date'] = self.report_date
            current_metrics_in_pivot = [col for col in original_metric_order if col in df_pivoted.columns]
            ordered_columns = ['Date', 'Table Name'] + current_metrics_in_pivot
            df_pivoted = df_pivoted.reindex(columns=[col for col in ordered_columns if col in df_pivoted.columns])
            pivoted_dfs_list.append(df_pivoted)

        if not pivoted_dfs_list:
             raise ValueError("Error (Regional Summary): Pivoting resulted in no DataFrames.")
        final_output_df = pd.concat(pivoted_dfs_list, ignore_index=True)
        non_numeric_metrics = ['Time Of Maximum Demand Met', 'SolarHR Max Demand Time', 'Non-SolarHR Max Demand Time']
        for col in final_output_df.columns:
            if col not in ['Date', 'Table Name'] and col not in non_numeric_metrics:
                final_output_df[col] = pd.to_numeric(final_output_df[col], errors='coerce')
        return final_output_df


    def transform_inter_region(self, raw_df_orig):
        # Correction: Raw table has 9 columns, including 'Sl.No.'
        if raw_df_orig.shape[1] != 9:
            raise ValueError(f"Error (Inter-Region): Expected 9 columns in raw table, got {raw_df_orig.shape[1]}.")
        
        # Drop the first 'Sl.No.' column
        df = raw_df_orig.iloc[:, 1:].copy() # Now df has 8 columns

        current_import_region_header = None
        processed_rows_data = []

        # This loop processes the 8-column DataFrame (after Sl.No. drop)
        for i in range(df.shape[0]):
            try:
                row_series = df.iloc[i] # This is a 8-element series
                nan_count = row_series.isna().sum()
                
                # Placeholder for the 9 data values for the current row
                current_row_values = [pd.NA] * 9 

                if nan_count > 7: # Typically means it's an "Import Region" header like "ER-NR"
                    current_import_region_header = row_series.dropna().iloc[0] if not row_series.dropna().empty else current_import_region_header
                    continue
                elif nan_count > 5 and nan_count <= 7: # Data row needing alignment
                    non_na_values = row_series.dropna().tolist()
                    print(f"Row {i}: Found {len(non_na_values)} non-null values: {non_na_values}")  # Debug print
                    
                    # Map values to their correct positions based on target_csv_cols
                    # Only assign values if we have them
                    if len(non_na_values) > 0:
                        current_row_values[1] = non_na_values[0]  # Line Details (index 1)
                    if len(non_na_values) > 1:
                        current_row_values[5] = non_na_values[1]  # Import (MU) (index 5)
                    if len(non_na_values) > 2:
                        current_row_values[6] = non_na_values[2]  # Export (MU) (index 6)
                    if len(non_na_values) > 3:
                        current_row_values[7] = non_na_values[3]  # NET Import (MU) (index 7)
                else: # Regular data row
                    # For regular rows, ensure we have exactly 8 values before assigning
                    row_values = row_series.tolist()
                    if len(row_values) == 8:
                        current_row_values[:8] = row_values
                    else:
                        print(f"Warning: Row {i} has {len(row_values)} values instead of 8")
                        # Pad or truncate to 8 values
                        current_row_values[:8] = row_values[:8] + [pd.NA] * (8 - len(row_values))
                
                current_row_values[8] = current_import_region_header # Assign 'Import' region to the 9th position
                processed_rows_data.append(current_row_values)
                
            except Exception as e:
                print(f"Error processing row {i}: {str(e)}")
                print(f"Row data: {row_series.tolist() if 'row_series' in locals() else 'Not available'}")
                continue
        
        if not processed_rows_data:
            print("Warning (Inter-Region): No data rows processed. Returning empty DataFrame.")
            return self._add_common_cols(pd.DataFrame(), 'Inter-Region')

        try:
            df_processed = pd.DataFrame(processed_rows_data)
            target_csv_cols = ['Voltage Level', 'Line Details', 'No. of Circuit', 
                              'Max Import (MW)', 'Max Export (MW)', 'Import (MU)', 
                              'Export (MU)', 'NET Import (MU)', 'Import'] # 9 columns

            if df_processed.shape[1] != len(target_csv_cols):
                raise ValueError(f"Error (Inter-Region): Processed data column count mismatch. Expected {len(target_csv_cols)}, got {df_processed.shape[1]}.")
            df_processed.columns = target_csv_cols
            
            df_processed = df_processed.dropna(thresh=max(1, len(target_csv_cols) - 5))
            numeric_cols = ['No. of Circuit', 'Max Import (MW)', 'Max Export (MW)', 
                           'Import (MU)', 'Export (MU)', 'NET Import (MU)']
            for col in numeric_cols:
                if col in df_processed.columns:
                    df_processed[col] = pd.to_numeric(df_processed[col], errors='coerce')
            
            df_processed = self._add_common_cols(df_processed, 'Inter-Region')
            final_ordered_columns = ['Date', 'Table Name', 'Import'] + \
                                  [col for col in target_csv_cols if col != 'Import']
            
            # Correction: Ensure final table has columns exactly as in final_ordered_columns
            if not all(col in df_processed.columns for col in final_ordered_columns) or \
               len(df_processed.columns) != len(final_ordered_columns):
                missing_cols = [col for col in final_ordered_columns if col not in df_processed.columns]
                extra_cols = [col for col in df_processed.columns if col not in final_ordered_columns]
                raise ValueError(
                    f"Error (Inter-Region): Final column structure mismatch. "
                    f"Expected: {final_ordered_columns}. Got: {df_processed.columns.tolist()}. "
                    f"Missing: {missing_cols}, Extra: {extra_cols}."
                )
            return df_processed[final_ordered_columns]
            
        except Exception as e:
            print(f"Error in final processing: {str(e)}")
            print(f"Processed data shape: {df_processed.shape if 'df_processed' in locals() else 'Not available'}")
            raise

    def transform_international_exchange(self, raw_df):
        df = raw_df.copy()
        if df.empty:
            # raise ValueError("Error (International Exchange): Raw table is empty.")
            print("Warning (International Exchange): Raw table is empty. Returning empty DataFrame.")
            return self._add_common_cols(pd.DataFrame(), 'International')


        # Assumes header is in the first row of tabula's output
        df_header = self._clean_column_names(df.iloc[0])
        df_data = df.iloc[1:].copy() # Make a copy for modification
        df_data.columns = df_header # Assign cleaned header to the rest of the data
        df = df_data.reset_index(drop=True)

        target_cols_final = ['State', 'Region', 'Line Name', 'Max (MW)', 
                             'Min (MW)', 'Avg (MW)', 'Energy Exchange (MU)']

        # Correction: Direct column assignment if count matches, else error.
        if df.shape[1] != len(target_cols_final):
            raise ValueError(
                f"Error (International Exchange): Column count mismatch after header assignment. "
                f"Expected {len(target_cols_final)} based on target, got {df.shape[1]} from data ({df.columns.tolist()})."
            )
        df.columns = target_cols_final # Assign target names, assuming order is correct

        if 'State' in df.columns: # Now 'State' is a target column name
            idx_to_shift = df.index[df['State'].astype(str).str.contains('ER', na=False)]
            for i in idx_to_shift:
                df.iloc[i,:] = df.iloc[i,:].astype(str).shift(1, fill_value=pd.NA)
            df['State'] = df['State'].replace('', pd.NA).ffill()
            if 'Region' in df.columns:
                df['Region'] = df['Region'].replace('', pd.NA).ffill()
        
        if 'State' in df.columns:
             df = df[~df['State'].astype(str).str.contains('Total', na=False, case=False)].copy()
        
        numeric_cols = ['Max (MW)', 'Min (MW)', 'Avg (MW)', 'Energy Exchange (MU)']
        for col in numeric_cols:
            if col in df.columns: # Should exist due to direct assignment
                df[col] = pd.to_numeric(df[col], errors='coerce')

        df = self._add_common_cols(df, 'International')
        final_ordered_columns = ['Date', 'Table Name'] + target_cols_final
        # Final check already implicitly handled by df.columns = target_cols_final if counts match
        return df[final_ordered_columns]


    def transform_exchange(self, raw_df_export, raw_df_import, raw_df_net):
        all_exchange_dfs = []

        def process_single_exchange_table(df_raw_single, exchange_type):
            df_single_processed = df_raw_single.copy()
            if df_single_processed.shape[0] <= 3: # Need more than 3 rows to skip 3
                 print(f"Warning (Exchange - {exchange_type}): Not enough rows (<=3) to process. Skipping.")
                 return pd.DataFrame()
            
            df_single_processed = df_single_processed.iloc[3:, :].reset_index(drop=True)
            if df_single_processed.empty: # check if empty after slicing
                print(f"Warning (Exchange - {exchange_type}): Became empty after skipping first 3 rows. Skipping.")
                return pd.DataFrame()

            raw_cols_exchange = ['Country', 'PPA', 'Bilateral', 'DAM IEX', 'DAM PXIL', 
                                 'DAM HPX', 'RTM IEX', 'RTM PXIL', 'RTM HPX', 'Total']
            
            if df_single_processed.shape[1] != len(raw_cols_exchange):
                raise ValueError(
                    f"Error (Exchange - {exchange_type}): Column count mismatch. "
                    f"Expected {len(raw_cols_exchange)}, got {df_single_processed.shape[1]}."
                )
            df_single_processed.columns = raw_cols_exchange

            # Correction: Do NOT filter out "Total" in 'Country' column.
            # df_single_processed = df_single_processed[~df_single_processed['Country'].astype(str).str.contains('Total', na=False, case=False)].copy()

            df_single_processed['Type'] = exchange_type
             # Correction: Use 'Exchange' not 'Excchange'
            df_single_processed = self._add_common_cols(df_single_processed, 'Exchange')
            
            expected_cols_sub_table = ['Date', 'Table Name', 'Type'] + raw_cols_exchange
            # Ensure all columns are present (should be, due to assignment and addition)
            for col in expected_cols_sub_table:
                if col not in df_single_processed.columns: # Should not happen
                    df_single_processed[col] = pd.NA 
            return df_single_processed[expected_cols_sub_table]

        # (Processing logic for each exchange type, appending to all_exchange_dfs)
        # ... (similar to previous, calling process_single_exchange_table)
        df_export = process_single_exchange_table(raw_df_export, 'Export')
        if not df_export.empty: all_exchange_dfs.append(df_export)
        df_import = process_single_exchange_table(raw_df_import, 'Import')
        if not df_import.empty: all_exchange_dfs.append(df_import)
        df_net = process_single_exchange_table(raw_df_net, 'NET')
        if not df_net.empty: all_exchange_dfs.append(df_net)


        if not all_exchange_dfs:
            # raise ValueError("Error (Exchange): All sub-tables (Export, Import, NET) resulted in empty DataFrames.")
            print("Warning (Exchange): All sub-tables (Export, Import, NET) were empty or malformed. Returning empty DataFrame.")
            return pd.DataFrame()


        combined_df = pd.concat(all_exchange_dfs, ignore_index=True)
        numeric_cols_exchange = ['PPA', 'Bilateral', 'DAM IEX', 'DAM PXIL', 'DAM HPX', 
                                 'RTM IEX', 'RTM PXIL', 'RTM HPX', 'Total']
        for col in numeric_cols_exchange:
            if col in combined_df.columns:
                combined_df[col] = pd.to_numeric(combined_df[col], errors='coerce')
        return combined_df


    def transform_block_wise(self, raw_df):
        df = raw_df.copy()
        header_row_start_idx = -1
        # (Header finding logic as before)
        for r_idx in range(min(df.shape[0], 5)):
            row_str = " ".join(df.iloc[r_idx].astype(str).fillna('').str.strip().tolist())
            if "TIME" in row_str and "FREQUENCY" in row_str and "DEMAND MET" in row_str:
                header_row_start_idx = r_idx
                break
        
        new_header_from_pdf = []
        if header_row_start_idx != -1:
            if header_row_start_idx + 1 < df.shape[0]:
                top_header_series = df.iloc[header_row_start_idx].astype(str).fillna('')
                bottom_header_series = df.iloc[header_row_start_idx + 1].astype(str).fillna('')
                temp_new_columns = []
                for i in range(len(top_header_series)):
                    top_part = top_header_series.iloc[i].strip()
                    bottom_part = bottom_header_series.iloc[i].strip() if i < len(bottom_header_series) else ''
                    combined_name = bottom_part
                    if top_part and top_part != bottom_part:
                        combined_name = f"{top_part} {bottom_part}".strip()
                    elif not bottom_part and top_part:
                        combined_name = top_part
                    temp_new_columns.append(combined_name)
                new_header_from_pdf = self._clean_column_names(temp_new_columns)
                df = df.iloc[header_row_start_idx + 2:].reset_index(drop=True)
            else:
                new_header_from_pdf = self._clean_column_names(df.iloc[header_row_start_idx])
                df = df.iloc[header_row_start_idx + 1:].reset_index(drop=True)
        else:
            if df.empty: raise ValueError("Error (Block-wise): Raw table is empty and no header found.")
            new_header_from_pdf = self._clean_column_names(df.iloc[0]) # Fallback
            df = df.iloc[1:].reset_index(drop=True)
        
        df.columns = new_header_from_pdf # Assign header derived from PDF

        # Correction: Map to standard CSV names. Ensure length match.
        # The keys are the expected *cleaned* headers from PDF (new_header_from_pdf).
        # The values are the *final* CSV column names.
        # This map needs to be accurate based on how new_header_from_pdf is formed.
        # This example assumes new_header_from_pdf matches keys of column_mapping_block_wise.
        standard_csv_names_map = { 
            # This map's KEYS should match the typical cleaned output of the multi-line header logic above.
            # Its VALUES are the desired final column names.
            'TIME': 'TIME',
            'FREQUENCY HZ': 'FREQUENCY (Hz)', # Example: if cleaned header is 'FREQUENCY HZ'
            'DEMAND MET MW': 'DEMAND MET (MW)',
            'NUCLEAR MW': 'NUCLEAR (MW)',
            'WIND MW': 'WIND (MW)',
            'SOLAR MW': 'SOLAR (MW)',
            'HYDRO MW': 'HYDRO (MW)',
            'GAS MW': 'GAS (MW)',
            'THERMAL MW': 'THERMAL (MW)',
            'OTHERS MW': 'OTHERS* (MW)', # Note: asterisk might be cleaned by _clean_column_names
            'NET DEMAND MET MW': 'NET DEMAND MET (MW)',
            'TOTAL GENERATION MW': 'TOTAL GENERATION (MW)',
            'NET TRANSNATIONAL EXCHANGE MW +VE IMPORT -VE EXPORT': 'NET TRANSNATIONAL EXCHANGE (MW) (+ve) Import, (-ve) Export'
        }

        if len(df.columns) != len(standard_csv_names_map):
            raise ValueError(
                f"Error (Block-wise): Column count after PDF header processing ({len(df.columns)}) "
                f"does not match expected count for mapping ({len(standard_csv_names_map)}). "
                f"Actual columns: {df.columns.tolist()}"
            )
        # Assuming the order of df.columns matches the intended order of keys in standard_csv_names_map
        df.columns = list(standard_csv_names_map.values())

        numeric_cols_block_wise = [
            'FREQUENCY (Hz)', 'DEMAND MET (MW)', 'NUCLEAR (MW)', 'WIND (MW)', 'SOLAR (MW)',
            'HYDRO (MW)', 'GAS (MW)', 'THERMAL (MW)', 'OTHERS* (MW)', 'NET DEMAND MET (MW)',
            'TOTAL GENERATION (MW)', 'NET TRANSNATIONAL EXCHANGE (MW) (+ve) Import, (-ve) Export'
        ]
        for col in numeric_cols_block_wise:
            if col in df.columns:
                df[col] = df[col].astype(str).str.replace(',', '', regex=False).str.strip()
                df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

        df = self._add_common_cols(df, 'Block-wise')
        final_cols_block_wise = ['Date', 'Table Name', 'TIME'] + numeric_cols_block_wise
        
        # Correction: Ensure final table has exactly these columns
        if not all(col in df.columns for col in final_cols_block_wise) or \
           len(df.columns) != len(final_cols_block_wise):
            missing_cols = [col for col in final_cols_block_wise if col not in df.columns]
            extra_cols = [col for col in df.columns if col not in final_cols_block_wise]
            raise ValueError(
                f"Error (Block-wise): Final column structure mismatch. "
                f"Expected: {final_cols_block_wise}. Got: {df.columns.tolist()}. "
                f"Missing: {missing_cols}, Extra: {extra_cols}."
            )
        return df[final_cols_block_wise]


# --- Main Orchestrator ---

def main_pdf_processing_logic(pdf_path: str) -> list:
    """
    Orchestrates the entire PDF parsing workflow:
    1. Extracts raw tables and report date.
    2. Identifies and preprocesses raw tables.
    3. Transforms tables using PSPTransformer.
    4. Returns a list of processed DataFrames.
    (Note: CSV export is currently commented out).
    """
    logger.info(f"Airflow task: Starting PDF processing for: {pdf_path}")
    try:
        raw_tables_dict, report_date = extract_and_process_tables(pdf_path)
    except Exception as e:
        logger.error(f"Error during PDF processing: {e}")
        return []
    
    if not raw_tables_dict:
        logger.error("No tables extracted from PDF. Exiting process.")
        return [] # Return empty list if no raw tables

    identified_tables = identify_and_preprocess_raw_tables(raw_tables_dict)
    if not identified_tables:
        logger.error("No tables identified for transformation. Exiting process.")
        return [] # Return empty list if no tables identified

    # Debug: Print column names of identified tables to check tabula's output before transformation
    for name, table_df in identified_tables.items():
        logger.info(f"Identified Table '{name}' with columns: {table_df.columns.tolist()} and shape {table_df.shape}")


    transformer = PSPTransformer(report_date)
    final_dfs_list = [] # List to hold all successfully transformed DataFrames

    # --- Conditional Transformation Calls ---
    # Each transformation is called only if its required source table(s) were identified.

    # Regional Summary (complex, multiple sources)
    required_regional_tables = [
        'A. Power Supply Position at All India and Regional level',
        'B. Frequency Profile (%)',
        'E. Import/Export by Regions (in MU) - Import(+ve)/Export(-ve); OD(+)/UD(-)',
        'F. Generation Outage(MW)',
        'G. Sourcewise generation (Gross) (MU)',
        'G. Share of RE and Non-fossil',
        'H. All India Demand Diversity Factor',
        'I. All India Peak Demand and shortage at Solar and Non-Solar Hour'
    ]
    if all(table_name in identified_tables for table_name in required_regional_tables):
        try:
            df_regional = transformer.transform_regional_summary(
                identified_tables['A. Power Supply Position at All India and Regional level'],
                identified_tables['B. Frequency Profile (%)'],
                identified_tables['E. Import/Export by Regions (in MU) - Import(+ve)/Export(-ve); OD(+)/UD(-)'],
                identified_tables['F. Generation Outage(MW)'],
                identified_tables['G. Sourcewise generation (Gross) (MU)'],
                identified_tables['G. Share of RE and Non-fossil'],
                identified_tables['H. All India Demand Diversity Factor'],
                identified_tables['I. All India Peak Demand and shortage at Solar and Non-Solar Hour']
            )
            if not df_regional.empty:
                final_dfs_list.append(df_regional)
                logger.info("Regional Summary transformation successful.")
        except Exception as e:
            logger.error(f"Error during Regional Summary transformation: {e}")
    else:
        logger.info("Skipping Regional Summary transformation due to missing one or more source tables.")

    # States Table
    if 'C. Power Supply Position in States' in identified_tables:
        try:
            df_states = transformer.transform_states(identified_tables['C. Power Supply Position in States'])
            if not df_states.empty:
                final_dfs_list.append(df_states)
                logger.info("States transformation successful.")
        except Exception as e:
            logger.error(f"Error during States transformation: {e}")
    else:
        logger.info("Skipping States transformation (source table 'C. Power Supply Position in States' missing).")
    
    # International NET Table
    if 'D. Transnational Exchanges (MU) - Import(+ve)/Export(-ve)' in identified_tables:
        try:
            df_international_net = transformer.transform_international_net(
                identified_tables['D. Transnational Exchanges (MU) - Import(+ve)/Export(-ve)']
            )
            if not df_international_net.empty:
                final_dfs_list.append(df_international_net)
                logger.info("International NET transformation successful.")
        except Exception as e:
            logger.error(f"Error during International NET transformation: {e}")
    else:
        logger.info("Skipping International NET transformation (source table 'D. Transnational Exchanges...' missing).")

    # Inter-Region Table
    if 'Intra-national Exchange' in identified_tables:
        try:
            df_inter_region = transformer.transform_inter_region(identified_tables['Intra-national Exchange'])
            if not df_inter_region.empty:
                final_dfs_list.append(df_inter_region)
                logger.info("Inter-Region transformation successful.")
        except Exception as e:
            logger.error(f"Error during Inter-Region transformation: {e}")

    else:
        logger.info("Skipping Inter-Region transformation (source table 'Intra-national Exchange' missing).")

    # International Exchange Table
    if 'International Exchange' in identified_tables:
        try:
            df_international = transformer.transform_international_exchange(identified_tables['International Exchange'])
            if not df_international.empty:
                final_dfs_list.append(df_international)
                logger.info("International Exchange transformation successful.")
        except Exception as e:
            logger.error(f"Error during International Exchange transformation: {e}")
    else:
        logger.info("Skipping International Exchange transformation (source table 'International Exchange' missing).")

    # "Excchange" Table (combining Export, Import, Net from India)
    required_exchange_tables = [
        'Export From India (in MU)', 'Import by India(in MU)', 'Net from India(in MU)'
    ]
    if all(table_name in identified_tables for table_name in required_exchange_tables):
        try:
            df_exchange = transformer.transform_exchange(
                identified_tables['Export From India (in MU)'],
                identified_tables['Import by India(in MU)'],
                identified_tables['Net from India(in MU)']
            )
            if not df_exchange.empty: # transform_exchange can return 0 if malformed
                final_dfs_list.append(df_exchange)
                logger.info("Exchange transformation successful.")
        except Exception as e:
            logger.error(f"Error during Excchange transformation: {e}")
    else:
        logger.info("Skipping Excchange transformation due to missing one or more source tables.")

    # Block-wise Table
    block_wise_table_name = '15 Min (INSTANTANEOUS) ALL INDIA GRID FREQUENCY, GENERATION & DEMAND MET (SCADA DATA)'
    if block_wise_table_name in identified_tables:
        try:
            df_block_wise = transformer.transform_block_wise(identified_tables[block_wise_table_name])
            if not df_block_wise.empty:
                final_dfs_list.append(df_block_wise)
                logger.info("Block-wise transformation successful.")
        except Exception as e:
            logger.error(f"Error during Block-wise transformation: {e}")
    else:
        logger.info(f"Skipping Block-wise transformation (source table '{block_wise_table_name}' missing).")

    # The script now returns a list of DataFrames.
    # CSV combination and export logic is currently commented out.
    if not final_dfs_list:
        logger.error("No tables were successfully processed and transformed.")
    else:
        logger.info(f"Airflow task: PDF processing finished for: {pdf_path}. Found {len(final_dfs_list)} tables.")
    
    # To re-enable CSV export:
    # if final_dfs_list:
    #     try:
    #         final_combined_df = pd.concat(final_dfs_list, ignore_index=True)
    #         output_dir = "sample output"
    #         os.makedirs(output_dir, exist_ok=True) # Create output directory if it doesn't exist
    #         output_path = os.path.join(output_dir, "Processed_PSP_from_Tabula_Updated.csv")
    #         final_combined_df.to_csv(output_path, index=False)
    #         print(f"Combined data saved to {output_path}")
    #         # return final_combined_df # Optionally return the combined DataFrame
    #     except Exception as e:
    #         print(f"Error during final DataFrame concatenation or CSV export: {e}")
    # else:
    #     print("No tables were processed for final combination into CSV.")
    #     # return pd.DataFrame() # Return empty DataFrame if nothing to combine
    
        
    return final_dfs_list # Current behavior: returns list of DFs

# --- Script Execution ---
if __name__ == "__main__":
    processed_data_list = main_pdf_processing_logic(pdf_path="sample input/18.04.25_NLDC_PSP.pdf") # This will be a list of DataFrames

    # Example: Inspect the first few processed DataFrames if any
    if processed_data_list:
        print(f"\n--- {len(processed_data_list)} DataFrame(s) processed ---")
        for i, df_item in enumerate(processed_data_list[:3]): # Print info for first 3 DFs
            print(f"\n--- DataFrame {i+1} (Table Name: {df_item['Table Name'].iloc[0] if not df_item.empty else 'N/A'}) ---")
            print(f"Shape: {df_item.shape}")
            print(df_item.head())
            print(df_item.info())
            
        # If you want to combine them into one DataFrame for inspection or saving:
        # final_df_combined_for_debug = pd.concat(processed_data_list, ignore_index=True)
        # print("\n--- Combined DataFrame for Debug (Info) ---")
        # print(final_df_combined_for_debug.info())
        # print("\n--- Value Counts for 'Table Name' in Combined Debug DF ---")
        # print(final_df_combined_for_debug['Table Name'].value_counts())

    else:
        logger.error("\nNo data was processed by the script.")

    # Keep the console open for interactive inspection if needed (useful during development)
    logger.info("\nDropping into interactive console. Type exit() or Ctrl-D to quit.")
    # Use `processed_data_list` to inspect the list of DataFrames.
    import code
    code.interact(local=locals())